### ISSUE TITLE
ValveBase missing POS_STATE_RBV component?

### ISSUE THREAD

**Issue by klauer** [pcdshub/pcdsdevices#1041]
## Potential Issue

For ValveBase:

https://github.com/pcdshub/pcdsdevices/blob/c5c93cdbed78d56687910b688f4db7594cd24c28/pcdsdevices/valve.py#L85

This component in another device:
https://github.com/pcdshub/pcdsdevices/blob/c5c93cdbed78d56687910b688f4db7594cd24c28/pcdsdevices/valve.py#L400-L405

Seems like it should also be present in ValveBase, based on the vacuum library code:

https://github.com/pcdshub/lcls-twincat-vacuum/blob/c9fae6cce7c3bf995af6bcc8ef46221db2fd50dc/L2SIVacuum/DUTs/Valves/ST_ValveBase.TcDUT#L78-L88

## Question

Any reason not to have it in pcdsdevices? I assume it's not required in general because we utilize pcdswidgets to view the valve state for the most part.

## Context

I generated a set of simulation valves for [sim-ioc](https://github.com/pcdshub/sim-ioc) and found that this PV was missing for VGC (at least).

**Comment by klauer** [comment]
@ghalym - can `valve_position` go in `ValveBase` (see the above for details)?

**Comment by ghalym** [comment]
@klauer I don't recall why it isn't in pcdsdevices, maybe an oversight. I agree it should be added there.
