### ISSUE TITLE
PIMMotor in 'unknown' mode registers as inserted

### ISSUE THREAD

**Issue by teddyrendahl** [pcdshub/pcdsdevices#107]
## Expected Behavior

If the PIMMotor is `unknown` it should report neither inserted or removed. 

## Current Behavior

If PIMMotor is 'unknown' it registers as `inserted`.

## Possible Solution

```python
def inserted(self):
     return self.states.value in ('IN', 'DIODE')
```

**Comment by ZLLentz** [comment]
Solved with #136
