### ISSUE TITLE
SXR attenuator screens: "custom" energy does not toggle widget visibility

### ISSUE THREAD

**Issue by klauer** [pcdshub/pcdsdevices#1079]
## Current Behavior
For at1k4_calc and at2k2_calc, these screens exist:

<img width="583" alt="image" src="https://user-images.githubusercontent.com/5139267/200082571-72d545b7-aef0-40b8-8658-f9ddfbd61bd2.png">

These are embedded as [`AttenuatorCalculatorSXR_FourBlade_calc.ui`](https://github.com/pcdshub/pcdsdevices/blob/master/pcdsdevices/ui/AttenuatorCalculatorSXR_FourBlade_calc.ui).

## Expected Behavior

When the user clicks "Actual", the current LCLS photon energy should be used.
When the user clicks "Custom", a line edit widget allowing you to customize the photon energy for the calculation should be shown.

This is the rule:
<img width="785" alt="image" src="https://user-images.githubusercontent.com/5139267/200082790-ffd52740-92fd-4b41-879c-fc0e17163e91.png">
Where the enum is `ca://${prefix}:SYS:EnergySource`

## Possible Solution
* Unclear why the rule isn't firing to me.
* Could remove the rule and just always show the widget?

**Comment by ZLLentz** [comment]
Maybe there's some strange typing mismatch going on with how pydm and the rules each processes this channel's value

**Comment by klauer** [comment]
The PV hasn't changed in over a year, so I think it should be a regression in the rule handling mechanism itself

**Comment by ZLLentz** [comment]
the rule handling did get changed at some point (once? and back?) https://github.com/slaclab/pydm/issues/739
