### ISSUE TITLE
SXR attenuator screens: 4-blade calculator results not intuitive or clear

### ISSUE THREAD

**Issue by klauer** [pcdshub/pcdsdevices#1080]
## Expected Behavior

It should be obvious which filters the SXR solid attenuator calculator will insert from the provided user interface in pcdsdevices.
 
Currently, the calculator only indicates if _any_ filter will be inserted for the blade or not.

## Current Behavior

Here are two obvious examples, where the result of the calculator should be to either insert all filters or remove all filters:

A transmission of 0.0:

<img width="583" alt="image" src="https://user-images.githubusercontent.com/5139267/200083048-4fa4fe7c-1730-4d32-a332-e923f72a5302.png">

This is _okay_ at best, we still don't know which filter of the 4 per blade is going to be inserted.

A transmission of 1.0:

<img width="573" alt="image" src="https://user-images.githubusercontent.com/5139267/200083013-48ae55a4-89d4-49d2-9253-17a8ef0687f7.png">

This is the only scenario where we can say the display is unambiguous. All filters are removed. Full beam.

And a less obvious example - a transmission of 0.01:

<img width="582" alt="image" src="https://user-images.githubusercontent.com/5139267/200083244-9902b05d-cef0-4c15-af5f-2286b3db34f1.png">

1 filter inserted (but which one?)

## Possible Solution

Currently, the IOC only returns integer values for the filter number to be inserted. This does not include material or thickness information.

```
$ caget AT1K4:CALC:SYS:BestConfiguration_RBV
AT1K4:CALC:SYS:BestConfiguration_RBV 4             1 1 9 8
```
This means for the 4 blades: removed, removed, and filter 9, filter 8.

So:
* The IOC itself could be modified at some point
* For now, we could show the number of the filter to be inserted instead of the green/gray box. This isn't great from the user's perspective as they have to look at the filter options for that blade but is at least better than the current solution.

**Comment by ZLLentz** [comment]
There might also be a clever way to superimpose the filter number or some property of the filter such as the thickness and/or material on top of the indicator widget.

**Comment by klauer** [comment]
Here's my WIP change - if you can think of a nicer way, I'd like to know!
<img width="804" alt="image" src="https://user-images.githubusercontent.com/5139267/200090731-4b50c2ac-cbee-45ee-99d4-56af545457f0.png">
Rule-based, using that best configuration array as follows: `ch[0][2] == 1 and "Removed" or f"Insert {ch[0][2] - 1}"`

**Comment by ZLLentz** [comment]
My intuition is that it's not going to be possible to do better without some extra work that might not be possible in designer.

Something like a 2d indicator grid for example... Or some IOC extensions to add more precise helpful text. But a lot of the possibility space won't be clear if it's better or not until the work is mostly done.
