### ISSUE TITLE
Need a class for DUT_MotionPneumaticActuator, FB_MotionPneumaticActuator

### ISSUE THREAD

**Issue by ZLLentz** [pcdshub/pcdsdevices#1083]
## Expected Behavior

We need a class for controlling beckhoff pneumatic devices that are implemented using https://github.com/pcdshub/lcls-twincat-motion/blob/2644528a99a1857cd0cdaefd62f2612f10e35b9e/lcls-twincat-motion/Library/DUTs/DUT_MotionPneumaticActuator.TcDUT.

This is the crucial datatype embedded in https://github.com/pcdshub/lcls-twincat-motion/blob/2644528a99a1857cd0cdaefd62f2612f10e35b9e/lcls-twincat-motion/Library/POUs/Motion/FB_MotionPneumaticActuator.TcPOU

This is used for ST3K2, ST4K4, and ST5K4, so it only would control stoppers for now, but the underlying code is intended to be generic for pneumatic motion.

The class should contain helpful methods for inserting and removing these devices and lightpath support (inserted = blocking)

## Current Behavior

No such class exists. Existing stopper classes are not suitable for these devices.

## Possible Solution

Create a new device.

## Context

James Cryan in TMO tried to instantiate an ST4K4 device and found that no suitable class existed

## Your Environment

latest

**Comment by ZLLentz** [comment]
I suspect we want a generic beckhoff pneumatic-type device with references to the beckhoff motion lib and insert/remove helpers, then a specific stopper class that adds the lightpath info

**Comment by nrwslac** [comment]
This looks like a good issue to get back into some python. Mind if I take a stab at it? @ZLLentz

**Comment by ZLLentz** [comment]
@nrwslac go for it if it interests you, it's 100% fair game!
