### ISSUE TITLE
Prune gh-pages branch

### ISSUE THREAD

**Issue by klauer** [pcdshub/pcdsdevices#1103]
## Current Behavior
Our automated documentation building generated a lot of extraneous commits.
The git repository is quite large at this point.

## Possible Solution
I'd like to squash the entire history of `gh-pages` and remove intermediate commits to reduce the size a bit.

Thoughts?

**Comment by tangkong** [comment]
I wouldn't be opposed, I don't find that history particularly useful.   I guess we can just squash the history periodically, since there's probably no way to ... avoid making commits?

Is the size of the commit history causing issues somewhere?  Are we hitting a storage cap?

**Comment by klauer** [comment]
No cap is being hit. The slowness here irked me a bit - documentation checkout _from GitHub Actions_ takes 37 seconds:
<img width="563" alt="image" src="https://user-images.githubusercontent.com/5139267/212151321-8edd8a65-c4e5-4bf9-bab3-d38fd3c2a536.png">

The new GHA workflow will automatically squash commits between releases, so it should cut down on the size in the future.

**Comment by tangkong** [comment]
The ~250 commits in the gh-pages branch seems piddling in comparison to the ~5000 commits in the main branch, but I guess that's an improvement.  

Maybe we should squash each PR's commit history by default?  You could argue that pcdsdevices gets the most variation on commit quality/accuracy, and simply organizing by PR might be sufficient?

**Comment by klauer** [comment]
Take a look at `git log --stat origin/gh-pages` to see why the two branches aren't even remotely close in their per-commit size. 5000 commits isn't a big deal when only a file or two gets changed - but each commit is 500+ on gh-pages.

**Comment by tangkong** [comment]
ah right.. that makes a lot of sense.  🤦

**Comment by ZLLentz** [comment]
I'm :+1: on periodic squashing. Not only is the history not particularly useful as stated above, but I'm going to claim that the old tag documentations aren't so relevant either because nobody is using very very old versions in this repo specifically.

**Comment by klauer** [comment]
Pruned the branch and updated the versions.py/json files: https://github.com/pcdshub/pcdsdevices/tree/gh-pages
(If there are any issues once it gets deployed, I can always revert/fix it then)

**Comment by klauer** [comment]
Looks like it still works. Closing this issue until the next time...
