### ISSUE TITLE
TPR trigger channel, top level object, screens

### ISSUE THREAD

**Issue by slactjohnson** [pcdshub/pcdsdevices#1119]
## Current Behavior
We don't have anything for the TPR. 

## Expected Behavior
We should have support for the TPR equivalent to that of the EVR. 

## Context / environment
I have numerous devices that will require TPRs soon. So will lots of other people. 

## Suggested Solution
We should provide support equal to what is described in #1118 for the TPR. 

There's also a question of how do we deal with timing changing sources? Maybe this is done in the IOC and we don't have to worry? I haven't inspected the TPR IOC yet, and have only briefly played with one, so I don't quite know how this should be done yet. Bruce's EDM screens currently allow you to choose what type of timing you're using, and the screen updates appropriately. We will eventually need the same functionality in PyDM and the TPR class. 

/end confused rambling

**Comment by ZLLentz** [comment]
Requested again by James in https://jira.slac.stanford.edu/browse/ECS-3903

**Comment by ZLLentz** [comment]
Adding Kaushik to match the Jira assignment

**Comment by slactjohnson** [comment]
@KaushikMalapati can we close this now? I think your PR has been merged, right?

**Comment by KaushikMalapati** [comment]
> @KaushikMalapati can we close this now? I think your PR has been merged, right?

It has been, #1178.
