### ISSUE TITLE
EPICS Motor Record MSTA Field

### ISSUE THREAD

**Issue by slactjohnson** [pcdshub/pcdsdevices#1205]
## Current Behavior
We currently don't use the motor record MSTA field in our python class. 

## Expected Behavior
It would be nice to have _some_ insight into the MSTA field, particularly the "HOMED" bit: https://epics-modules.github.io/motor/motorRecord.html#Fields_status

## Context / environment
Some stages like SmarAct have homing routines that will simply time out, and it's not always easy to tell if the motor is really homed or if 
the home routine failed. This recently caused some confusion in the LHN BTS. 

Jira ticket here: https://jira.slac.stanford.edu/browse/ECS-4783

## Suggested Solution
It would be nice to add the home status to the python class, and potentially the motor widget used for screens.

**Comment by ZLLentz** [comment]
It should be possible to monitor the MSTA field and run a callback to forward some subset of the bits to dedicated signals that could then become indicators on the screen.

**Comment by slactjohnson** [comment]
This was completed in PR #1259
