### ISSUE TITLE
Base Velocity and Velocity Max missing from EpicsMotor base class in pcdsdevices.epics_motor

### ISSUE THREAD

**Issue by aberges-SLAC** [pcdshub/pcdsdevices#1224]
## Current Behavior
`<PV>:m<N>.VMAX` and `<PV>:m<N>.VBAS` are not ported over in `EpicsMotor` parent class. This means that if either of those PVs get set (like in the `edm` screens, for example...) then you run into unclear limitations to changing the velocities in inherited screens. This is particularly troublesome for SmarActs, as you become unable to uncap the velocities, or may even be inexplicably stuck at certain velocities if the `VBAS` was set erroneously.

## Expected Behavior
`VMAX` and `VBAS` PVs from `EpicsMotor` parent class available in a `kind=config` type signal in Typhos screens.

## Context / environment
After changing over the out-of-loop mechanical delay lines in the FTL to the typhos screens, users (myself included) were unable to change the velocities on several stages with no clear indicator as to why.

## Steps to Reproduce (for bugs)
1. `caput` the `VBAS` or `VMAX` to some nominal value (e.g. 1 mm/s)
2. Try to change the `velocity` signal in a `pcdsdevices.epics_motor.SmarAct` screen that is below either of those values

## Suggested Solution
Bring these two signals over in the `tab_whitelist` in the parent class to prevent this issue in the future.

**Comment by tangkong** [comment]
Does an attempt to change the velocity past its limits via python/ophyd just not yield an error message?

To be clear here, `.VBAS` and `.VMAX` are added in `IMS`, not in our epics motor base class (`PCDSMotorBase`) nor ophyd's base `EpicsMotor`.  

To add this would require moving the components from `IMS` to `PCDSMotorBase`, I believe.  Then we would have to adjust the tab whitelist as Adam suggests

**Comment by aberges-SLAC** [comment]
Nope, no error message just quiet failure, just let when you `caput` the velocity past its limits:
![image](https://github.com/pcdshub/pcdsdevices/assets/149725219/f9945cf5-ef69-4a11-84c5-22667e465ffa)
![image](https://github.com/pcdshub/pcdsdevices/assets/149725219/9a7b5df5-2778-41ec-9550-e059e3e7a51c)

https://github.com/pcdshub/pcdsdevices/assets/149725219/0fe9c1e3-7a48-49cf-bb6b-24223ba9072d

(NOTE: Status is invalid because I didn't jog the open-loop steps back and forth. They appear magenta on first start-up if they haven't received a command)
