### ISSUE TITLE
TprTrigger Class Not Connecting

### ISSUE THREAD

**Issue by slactjohnson** [pcdshub/pcdsdevices#1225]
## Current Behavior
The TprTrigger class appears to not be connecting to all signals. Instantiating the class and checking the `connected` attr gives false. 

This appears to be related to the `delay_setpoint` signal (see screenshot). When inspecting the PV, the FormattedComponent PV string does not appear to be getting completed, with `self.sys` not substituted. This appears to be defined almost identically to the `label` component, which _does_ work. 

![image](https://github.com/pcdshub/pcdsdevices/assets/29102919/fa984570-d03a-4fae-bd61-de492a6fbf24)

## Expected Behavior
All signals work. 

## Context / environment
I am trying to use the `ophyd.device.configure` method, but it seems to fail because of this device disconnection. 

![image](https://github.com/pcdshub/pcdsdevices/assets/29102919/4dde8e69-dc63-4c96-b748-4700a332b69a)

**Comment by tangkong** [comment]
Luckily we've walked this path before.  We can tell ophyd to fill fields other than the suffix with the `add_prefix` argument.
