### ISSUE TITLE
Test suite failures with numpy 2.0

### ISSUE THREAD

**Issue by ZLLentz** [pcdshub/pcdsdevices#1250]
## Current Behavior

Many of the test suites pick up numpy 2.0 and fail

## Expected Behavior

- We expect the test suite to fail only for issues with the code, not for issues with the test suite
- We expect everything to become numpy 2.0 compatible

## Context / environment

Makes the PRs look like they break everything but they don't...

## Steps to Reproduce (for bugs)

1. Install numpy 2.0
2. Run the test suite

## Suggested Solution

Update deprecated functions to the new ones specified in numpy 2.0
See https://numpy.org/devdocs/release/2.0.0-notes.html#numpy-2-0-python-api-removals

**Comment by ZLLentz** [comment]
After a closer look, the failure path is:

- import pint
- pint setup goes through pint.compat
- pint.compat imports everything everywhere
- dask gets imported and it fails with a numpy 2.0 compatibility issue

**Comment by ZLLentz** [comment]
It's worth considering whether it's time to stop using pint for these unit conversions
pint.compat has repeatedly given us various issues over the years when dependencies update, and it also incurs a large time penalty on import, due to importing things like pandas

**Comment by ZLLentz** [comment]
Note that the latest version of dask doesn't have the same issue, at the cost of needing to downgrade bluesky (because there's some mutual incompatible with the zict dependency)
Note also that the only reason we have dask in the dependency chain is because bluesky -> databroker -> dask and we basically don't use databroker

**Comment by ZLLentz** [comment]
Further, bluesky is a dependency only for the progress bar (and is used in the test suite for various things)

**Comment by tangkong** [comment]
We're not the only people that have grown weary of pint https://github.com/StephenWattam/pintless

**Comment by ZLLentz** [comment]
Interesting to see we're not alone in this- very happy with how easy pint is to use, less happy with performance (and in our case, with maintainability when putting pint in a large conda env)

**Comment by tangkong** [comment]
An interesting comparison table that might warrant some verification but is a good starting point for looking at alternatives
https://socialcompare.com/en/comparison/python-units-quantities-packages

**Comment by ZLLentz** [comment]
closed by #1253 but we can re-open and revisit if needed
