### ISSUE TITLE
XPP, XCS have need for CCM states

### ISSUE THREAD

**Issue by ZLLentz** [pcdshub/pcdsdevices#140]
Another reminder to include this in the hutch-specific repos:
```
class CCMRecordPositioner(InOutRecordPositioner):
    """ 
    Version of InOut device that has distinct states for CCM and PINK
    """
    states_list = ['OUT', 'CCM', 'PINK']
    in_states = ['PINK', 'CCM']
    _states_alias = {'PINK': 'IN'}


class PulsePickerCCM(PulsePickerInOut):
    """ 
    PulsePicker paired with a states record to control the Y position and
    manage the differing elevations for running in CCM or PINK mode.
    """
    inout = FCmp(CCMRecordPositioner, '{self._inout}')
```

**Comment by ZryletTC** [comment]
@ZLLentz Do you know if this is still applicable?

**Comment by silkenelson** [comment]
I think this may have to do with the CCM cause beam offset and changes to the set points of devices behind the CCM? That that XPP & XCS need a CCM state is obvious as only this hutches have a CCM.

**Comment by ZLLentz** [comment]
I'm not going to defend bad issue titles from years ago. I think this should be closed though.
