### ISSUE TITLE
InOutPVPositioner Inheritance does produce valid `device_tuple`

### ISSUE THREAD

**Issue by teddyrendahl** [pcdshub/pcdsdevices#157]
## Current Behavior

Currently when you create a `InOutPVPositioner` object and call `.get()` the command fails with an error message such as:
```
__new__() got an unexpected keyword argument 'your_signal'
```
On further investigation, the traceback reveals that this is raised while trying to create a `self._device_tuple` object. If you look at what this object actually is it looks like:
```
YourDeviceTuple(state, _1, _2, _3, _4)
```
I'm guessing the MRO of these class definitions does not produce a `DeviceTuple` that includes the signals attached by the child class. This causes an issue because when `get` tries to fill the tuple with `component_names` there are no spots in the tuple for all the components. It is worth noting that `component_names` contains **all** the signals, probably just not in time for the `_device_tuple` creation. 

## Your Environment

`ophyd == v1.1.0`

**Comment by ZLLentz** [comment]
Wow, did not expect this one

**Comment by ZLLentz** [comment]
@teddyrendahl to clarify, do you mean `InOutRecordPositioner` or `InOutPVStatePositioner`?

**Comment by ZLLentz** [comment]
I can confirm that both `PulsePicker` and `PIMMotor` seem to work for me. Which device failed?

**Comment by teddyrendahl** [comment]
Strange. Maybe I am the one in the wrong ... `InOutPvStatePositioner`

https://github.com/pcdshub/transfocate/blob/109c79f2dec69fc3c6ccdcec4f09d2d98c4fe5fd/transfocate/lens.py#L24

**Comment by teddyrendahl** [comment]
Confirmed that this works with `GateValve`. No idea how I am breaking this because I'm not even changing `__init__`.  Looks like this is my issue and mine alone.

**Comment by teddyrendahl** [comment]
This was caused entirely by having signal names with leading underscores...

**Comment by ZLLentz** [comment]
I'm surprised that the built in `namedtuple` considers leading underscores to be invalid names
