### ISSUE TITLE
Simulated YAG Motion

### ISSUE THREAD

**Issue by teddyrendahl** [pcdshub/pcdsdevices#16]
Simulated YAG motion should be greatly simplified to only move to specific states. No need to keep track of an internal readback / noise e.t.c. The main issue is the race condition:

https://travis-ci.org/slaclab/pswalker/jobs/258756164

Pretty obnoxious to keep restarting our CI checks...

**Comment by ZLLentz** [comment]
Closing because we aren't paying attention to these sim devices any more
