### ISSUE TITLE
Named Preset Positions

### ISSUE THREAD

**Issue by ZLLentz** [pcdshub/pcdsdevices#171]
## Expected Behavior

- All objects should be able to save named states that can be moved to
- The states should be loaded automatically at the start of a session
- Utility needs to be provided to move objects with the same state to the same state at the same time if grouped in a logical way
- There is an expectation that these state names become dynamically configurable methods

## Current Behavior
This feature was not implemented in Python 3 even though it gets heavy usage in the old hutch python libraries

## Implementation Ideas
- Perhaps something can be done to make States classes arbitrarily configurable on a axis

**Comment by teddyrendahl** [comment]
How are these stored? Do they persist between sessions?

**Comment by ZLLentz** [comment]
In the old python they are stored in json files and persist between sessions

**Comment by ZLLentz** [comment]
We need to proceed carefully to make sure this doesn't become as unmanageable and messy as the old implementation

**Comment by teddyrendahl** [comment]
Yeah. We should discuss. Absolutely see the need for the feature, just want to make sure that we do this in a way that is sustainable. I also realize this is a fringe goal but it would be nice if we could make sure this information is available in screens and other applications outside of hutch python

**Comment by ZLLentz** [comment]
TBH if there is a conceivable way to implement this in EPICS, I prefer that

**Comment by teddyrendahl** [comment]
Agree for archiving alone ...

**Comment by teddyrendahl** [comment]
Interesting idea that these presets live in the experiment file and we refuse to do it for permanent beamline devices

**Comment by ZLLentz** [comment]
I worry that this decision will have backlash unless we pair it with a ready plan to do something for the permanent devices.

**Comment by ZLLentz** [comment]
We did it
