### ISSUE TITLE
Tweak, Tweak2D

### ISSUE THREAD

**Issue by ZLLentz** [pcdshub/pcdsdevices#174]
## Expected Behavior

Old Python feature where you can use the arrow keys to manipulate motors

**Comment by teddyrendahl** [comment]
I actually kind of like this one 😄

**Comment by ZLLentz** [comment]
This is very easy to implement for the 1D tweak, it's less clear how to decide where and how to implement 2D tweak in a clean way

**Comment by teddyrendahl** [comment]
⬆️ for scientist request!

**Comment by ZLLentz** [comment]
description is:
1d tweak: `left` moves negative, `right` moves positive, `up` doubles step size, `down` halves step size
2d tweak: `left` moves x negatives, `right` moves x positive, `up` moves y positive, `down` moves y negative, and `shift+dir` changes the step size on that axis

**Comment by ZLLentz** [comment]
closed by #255
