### ISSUE TITLE
Fill in Motor Subdevices

### ISSUE THREAD

**Issue by ZLLentz** [pcdshub/pcdsdevices#177]
## Expected Behavior

Positioner subdevices should be included in classes like `PIM` whenever we know what they are. This gives us direct control over the motor in case we need it without having to instantiate a separate device.

**Comment by ZLLentz** [comment]
We should do this generically for `StateRecordPositioner` if possible

**Comment by teddyrendahl** [comment]
I think we could do this with `DynamicDeviceComponent` for fields in `CALC` records

**Comment by ZLLentz** [comment]
`DynamicDeviceComponent` creates a brand new class. We just need to create a specific `PCDSMotor` some time after the initialization.

**Comment by teddyrendahl** [comment]
I see. So some sort of take on a lazy `FormattedComponent`

**Comment by teddyrendahl** [comment]
⬆️ for scientist request!

**Comment by ZLLentz** [comment]
I'm browsing through the issues right now, this might actually be the most important thing to figure out...

**Comment by ZLLentz** [comment]
This is correct for the `PIM`, but not for the be lenses, which will need an xyz stack to do the calibration, 2d tweaking, etc... So we'll need to identify which ones should be organized in each way.

**Comment by ZLLentz** [comment]
`IPM`: separate (1 axis)
`Lens`: special class
`Lodcm`: separate (inf axis)
`PIM`: separate (4? axes)
`PulsePicker`: separate (2? axes)
`Slits`: separate (4 axes)

**Comment by ZLLentz** [comment]
Not a problem per se but I'd rather not make a thousand factories, we could do the simple generic factory e.g.
```
def fraken_device_factory(base_cls, **cpt):
    """
    Makes a subclass of ``base_cls`` with extra components attached

    Parameters
    ----------
    base_cls: ``Device``
        The base device that we want to extend

    **cpt: ``Component`` objects
        The components to add

    Returns
    -------
    franken_class: ``Device``
        A subclass of ``base_cls`` with extra components grafted on, like a mad scientist
    """
    pass

**Comment by ZLLentz** [comment]
I will say that any device that *needs* to have it's connections done or else the `__init__` will error out (e.g. area detector) will cause issues as a subdevice.

**Comment by klauer** [comment]
I might be able to help with this - maybe we should sit down and discuss the options.

**Comment by teddyrendahl** [comment]
@klauer 👍
