### ISSUE TITLE
Individual Device Logging

### ISSUE THREAD

**Issue by teddyrendahl** [pcdshub/pcdsdevices#193]
## Expected Behavior

Create loggers for individual device instances instead of using a module level logger. This would allow a handler to be applied to the behavior of individual device. This would be extremely nice for showing log messages in individual device screens.

```python
class IMS:
     """IMS with attached Log"""
     def __init__(self, prefix, *, name=None, **kwargs):
         super().__init__(prefix, name=name, **kwargs)
         self.log = logging.getLogger(__name__ + '.' + self.name)


# Options with log setup
logging.getLogger('pcdsdevices') # still included in this logger
motor = IMS('Tst:Mtr:1', name='Test Motor')
motor.log.addHandler(StreamHandler(level=logging.INFO)) # more specific logger
```

## Current Behavior

The smallest level you can subscribe is to the class module level i.e `pcdsdevices.epics_motor`

**Comment by teddyrendahl** [comment]
I think the hardest part will be picking logger name. It would be nice if the Device.log would also contain all child logs even if they are not in the same module. Maybe we check for `self.parent.log` and just use that if it is there?

**Comment by teddyrendahl** [comment]
Also I wonder if this is worth pushing back into `ophyd`

**Comment by ZLLentz** [comment]
Now you're trying to get really fancy, it's going to be hard to enable/disable logs for all `EpicsMotor` devices and subclasses with the normal Python logger that was built for per-module logging.

**Comment by ZLLentz** [comment]
It is totally feasible to have an `opyhd.epics_motor.EpicsMotor` log and then `ophyd.epics_motor.EpicsMotor.my_motor_name` logs

**Comment by teddyrendahl** [comment]
Right Right.

but if I have

```python
class XYZ
     x = Component(EpicsMotor, ...)
```
My class log will contain none of the log messages from the `x`. I'm suggesting:

```python
class Device:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if self.parent:
               self.log = self.parent.log
         else:
               self.log = logging.getLogger(self.__class__.__module__ + '.' + self.name)
```

**Comment by ZLLentz** [comment]
Ahh! That makes more sense. I like the concept. You could even pedantically separate all the subdevices e.g. 
```
class Device:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if self.parent:
               self.log = logging.getLogger(self.parent.log.name + '.' + self.name)
         else:
               self.log = logging.getLogger(self.__class__.__module__ + '.' + self.name)
```

**Comment by teddyrendahl** [comment]
After discussion, I am confident this is a good enough idea to push upstream to `ophyd`. Opening an issue there.

**Comment by teddyrendahl** [comment]
Closed by https://github.com/NSLS-II/ophyd/pull/526
