### ISSUE TITLE
Presets Documentation

### ISSUE THREAD

**Issue by teddyrendahl** [pcdshub/pcdsdevices#194]
## Expected Behavior

Couldn't find any user guide for this feature either in `hutch_python` or this repository. I'm not sure where it belongs specifically but we should have an explanation of this somewhere.

**Comment by ZLLentz** [comment]
I have neglected doing this because I couldn't decide where to put it. I figured we could do it post-release and update the docs without tagging the build.

**Comment by teddyrendahl** [comment]
Might just belong in `hutch_python` and refer to the actual directory structure. Probably worth having some docs in here just on how it works / setup in case people want to branch from our hypothetical setup.
