### ISSUE TITLE
IPM factory function

### ISSUE THREAD

**Issue by teddyrendahl** [pcdshub/pcdsdevices#203]
## Expected Behavior

The `IPM` IOC does not have any specific names for the targets therefore there is a large variance from hutch to hutch on naming conventions.

## Current Behavior

Must subclass `IPM` to change state names

## Possible Solution

Split up `IPM` and `IPMBase` where `IPMBase` is almost identical to its' current from with the exception of the `states_list` and `target_names`. `IPM` is then a factory function that creates an a class of type `IPMBase`  with these states specified. By setting the default states in this function to match the current `IPM` class we maintain back-compat ⛪️ 

### Note
All this applies to the `XFLS` class as well.

**Comment by ZLLentz** [comment]
Right now this can be a parameter on the main class. These only need to become factory functions once we commit to adding the set position and delta settings, which is when it becomes complicated because the enumerate states and the PVs for the set position match only 95% of the time... annoying.

**Comment by ZLLentz** [comment]
This is related to #150 and #148

**Comment by teddyrendahl** [comment]
I see. Fine for now as long as we set them before `super().__init__`?

**Comment by ZLLentz** [comment]
We should set them in `super().__init__`, e.g. one of the super classes should have a `states_list` parameter or an equivalent

**Comment by ZLLentz** [comment]
This way we solve the lens at the same time
