### ISSUE TITLE
Motor Wait Consistency

### ISSUE THREAD

**Issue by teddyrendahl** [pcdshub/pcdsdevices#213]
## Expected Behavior

We have a slight inconsistency in which motor commands wait by default and which don't.

* motor.move -> waits by default
* motor.mv , motor() -> do not wait by default

I can not recall if this was intentional or not? Should we just unify behind having wait be `False` by default everywhere?

**Comment by ZLLentz** [comment]
I also cannot recall the reasoning here. I suppose it should be consistent, and I'd rather it be consistently `False`.

**Comment by ZLLentz** [comment]
Has anyone asked for a `.wait` method yet?

**Comment by teddyrendahl** [comment]
Not yet.
