### ISSUE TITLE
PointingMirror states are broken

### ISSUE THREAD

**Issue by teddyrendahl** [pcdshub/pcdsdevices#214]
## Current Behavior
```
ValueError: 1 is not a valid state for xrt_m1h. Valid state names are: ['Unknown', 'IN'], and their corresponding values are [0, 2].
```
There is also the issue that these PVs exist but do not function. I will make these state-less mirrors for now in the `happi` config but this should be solved.

<details closed>
<summary> Full Traceback </summary>
<pre>
In [3]: xrt_m1h.inserted
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
/reg/neh/home4/trendahl/sandboxes/pcds/cxi/dev/devpath/pcdsdevices/state.py in get_state(self, value)
    211         try:
--> 212             return self.states_enum[value]
    213         except KeyError:

/reg/g/pcds/pyps/conda/py36/envs/pcds-1.0.0/lib/python3.6/enum.py in __getitem__(cls, name)
    326     def __getitem__(cls, name):
--> 327         return cls._member_map_[name]
    328 

KeyError: 1

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
/reg/neh/home4/trendahl/sandboxes/pcds/cxi/dev/devpath/pcdsdevices/state.py in get_state(self, value)
    214             try:
--> 215                 return self.states_enum(value)
    216             except ValueError:

/reg/g/pcds/pyps/conda/py36/envs/pcds-1.0.0/lib/python3.6/enum.py in __call__(cls, value, names, module, qualname, type, start)
    290         if names is None:  # simple value lookup
--> 291             return cls.__new__(cls, value)
    292         # otherwise, functional API: we're creating a new Enum type

/reg/g/pcds/pyps/conda/py36/envs/pcds-1.0.0/lib/python3.6/enum.py in __new__(cls, value)
    532         # still not found -- try _missing_ hook
--> 533         return cls._missing_(value)
    534 

/reg/g/pcds/pyps/conda/py36/envs/pcds-1.0.0/lib/python3.6/enum.py in _missing_(cls, value)
    545     def _missing_(cls, value):
--> 546         raise ValueError("%r is not a valid %s" % (value, cls.__name__))
    547 

ValueError: 1 is not a valid PointingMirrorStates

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
/reg/g/pcds/pyps/conda/py36/envs/pcds-1.0.0/bin/hutch-python in <module>()
----> 1 xrt_m1h.inserted

/reg/neh/home4/trendahl/sandboxes/pcds/cxi/dev/devpath/pcdsdevices/inout.py in inserted(self)
     52         True if the device is inserted
     53         """
---> 54         return self._pos_in_list(self.in_states)
     55 
     56     @property

/reg/neh/home4/trendahl/sandboxes/pcds/cxi/dev/devpath/pcdsdevices/inout.py in _pos_in_list(self, state_list)
    100 
    101     def _pos_in_list(self, state_list):
--> 102         current_state = self.get_state(self.position)
    103         for state in state_list:
    104             if current_state == self.get_state(state):

/reg/neh/home4/trendahl/sandboxes/pcds/cxi/dev/devpath/pcdsdevices/state.py in position(self)
    169         """
    170         state = self.state.get()
--> 171         state = self.get_state(state).name
    172         try:
    173             alias = self._states_alias[state]

/reg/neh/home4/trendahl/sandboxes/pcds/cxi/dev/devpath/pcdsdevices/state.py in get_state(self, value)
    406             self.states_enum = self._create_states_enum()
    407             self._has_checked_state_enum = True
--> 408         return super().get_state(value)
    409 
    410 

/reg/neh/home4/trendahl/sandboxes/pcds/cxi/dev/devpath/pcdsdevices/state.py in get_state(self, value)
    220                 enum_values = [state.value for state in self.states_enum]
    221                 raise ValueError(err.format(value, self.name, enum_names,
--> 222                                             enum_values))
    223 
    224     def _do_move(self, state):

ValueError: 1 is not a valid state for xrt_m1h. Valid state names are: ['Unknown', 'IN'], and their corresponding values are [0, 2].
</pre>
</details>

**Comment by ZLLentz** [comment]
Solved why the traceback is so butchered: we're setting state 1 to be both IN and OUT, and then setting state 2 to be both IN and OUT, overriding state 1... So we end up with state 1 being unoccupied and state 2 being IN and OUT.

**Comment by ZLLentz** [comment]
I am going to submit a PR for raising an exception if this happens, so we catch it early when the state definition is invalid
