### ISSUE TITLE
Ways to ease the transition from old set to new set

### ISSUE THREAD

**Issue by ZLLentz** [pcdshub/pcdsdevices#226]
In python2 hutch python, `set` adjusts the offset e.g. `motor.set(1)` changes the user readback to 1.

In `ophyd`, `motor.set(1)` moves the motor. This makes the transition confusing and potentially dangerous.

Diling asked if there was anything we could do about it. He suggested hiding `set` from tab-completion.
There may be other approaches, but I thought doing "something" to ease the transition is a reasonable request if we find a clean solution.

**Comment by ZLLentz** [comment]
Some solution prototyping as a last thing before heading out for the day. A failed attempt to circumvent IPython tab completion, a class that raises an exception if `set` is called outside of a `bluesky` plan, and a class that calls `set_position` if `set` is called outside of a `bluesky` plan. Pretty messy solution, but worth considering... I'd probably lean towards a combination of hide the completion and raise an exception. 
``` python
import inspect

from bluesky.callbacks.best_effort import BestEffortCallback
from bluesky.run_engine import RunEngine
from bluesky.plans import scan
from ophyd.positioner import SoftPositioner
import IPython


# This didn't work
class HideCompl(SoftPositioner):
    def __dir__(self):
        return [d for d in super().__dir__() if d != 'set']


def calling_names():
    """ 
    Return a list of the __name__ attributes up the frame stack.

    This should always start with __main__ and be ordered downward to the name
    of THIS file. Everything inbetween is useful information.
    """
    this_frame = inspect.currentframe()
    names = []
    while this_frame is not None:
        name = this_frame.f_globals['__name__']
        names.append(name)
        this_frame = this_frame.f_back
    return names


def called_by_run_engine():
    return 'bluesky.run_engine' in calling_names()


class BlockUser(SoftPositioner):
    def set(self, *args, **kwargs):
        if called_by_run_engine():
            return super().set(*args, **kwargs)
        else:
            raise RuntimeError('OY!')


class RedirUser(SoftPositioner):
    def set(self, *args, **kwargs):
        if called_by_run_engine():
            return super().set(*args, **kwargs)
        else:
            self.set_position(*args, **kwargs)

    def set_position(self, *args, **kwargs):
        print('redirected')


hide = HideCompl(name='hide')
block = BlockUser(name='block')
redir = RedirUser(name='redir')

RE = RunEngine({})
bec = BestEffortCallback()
RE.subscribe(bec)


def run_my_scan(motor):
    RE(scan([motor], motor, 0, 10, 11))


IPython.embed()
```

**Comment by klauer** [comment]
`set` isn't in our tab whitelist any longer. It looks like the above was the prototype for it.
Can this be closed?

**Comment by ZLLentz** [comment]
I think someone will ask for this again, but until they do I think we can close it
