### ISSUE TITLE
tests folder is installed as a full module

### ISSUE THREAD

**Issue by ZLLentz** [pcdshub/pcdsdevices#239]
Uh... weird thing here. Since there is an `__init__.py` file in the tests folder, the `find_packages()` method used in `setup.py` thinks it's a standalone module, and it gets installed as the `tests` module!

Perhaps it's time to move this into the subfolder and include it in the full distribution.

**Comment by teddyrendahl** [comment]
Why does that folder have an `__init__`? That seems like more of the issue, rather than the directory hierarchy itself

**Comment by ZLLentz** [comment]
Because I'm storing helpful test classes in there! Which is why I want to move it into the module.

**Comment by teddyrendahl** [comment]
Might prefer the latter. I find it kind of annoying to dig too deep to find tests. Plus a clear separation between "this is useful for these test alone" and "this can be used elsewhere because we promise to keep it stable"

**Comment by ZLLentz** [comment]
Fair enough
