### ISSUE TITLE
PPSStopper has move options

### ISSUE THREAD

**Issue by teddyrendahl** [pcdshub/pcdsdevices#259]
The `lightpath` looks to see if objects have `remove` and `insert` methods to see if they should have corresponding widgets. Currently the `PPSStopper` has the both of these and they just raise an Exception.

Can we remove these methods while still inheriting? Can we do something intelligent if `state` is a read-only signal?

**Comment by ZLLentz** [comment]
There isn't a clean/thorough way to remove a method from a subclass. We can override them with `None` and modify `__dict__` or `__dir__` to make them harder to find, or we can have a versions of the inout classes with no `insert`/`remove` and inherit from those for devices like this. After all, `inout.py` existly largely for the benefit of the `lightpath`.

**Comment by teddyrendahl** [comment]
Is it worth it? Should I just check if the `state` is `RO` in lightpath?

**Comment by ZLLentz** [comment]
Is that consistent enough to be usable? Does `happi` already know about the `state` signal?

**Comment by teddyrendahl** [comment]
Are we overthinking this? Can I just use `check_value`?

**Comment by ZLLentz** [comment]
If we implemented `check_value` correctly, then we can use it.
