### ISSUE TITLE
Attenuator Class Naming

### ISSUE THREAD

**Issue by teddyrendahl** [pcdshub/pcdsdevices#264]
## Expected Behavior

Attenuators classes generated by the factory should have nice  names like ... `AttenuatorFilters6`

## Current Behavior

`Attenuator123456`

**Comment by ZLLentz** [comment]
Stuff like this *feels* like super critical priority... but medium priority is correct.

**Comment by teddyrendahl** [comment]
Realizing that our class names are ugly enough that `[type(obj)._name__ for  obj in beampath]` might not be ideal ...
