### ISSUE TITLE
FltMvInterface missing from calculated axes

### ISSUE THREAD

**Issue by ZLLentz** [pcdshub/pcdsdevices#280]
The raw `PseudoPositioner` and `PseudoSingle` don't have our extra move functions, so they aren't currently included in any of our calculated axes.

**Comment by klauer** [comment]
Resolved in 6493751391499f810b8f79942f4e5bc41f6d5fc1, 1b27e4e23201a7f52bc24ad53d4c0a2d53a1f631, and maybe a couple others.
