### ISSUE TITLE
cf_units renamed to cf-units

### ISSUE THREAD

**Issue by ZLLentz** [pcdshub/pcdsdevices#318]
Need to change the dependency name... if we want to pick up the latest bugfix

**Comment by klauer** [comment]
It's not important, but this issue reminded me about it:

The only thing blocking me from getting pcdsdevices importing locally on my OSX machine was cf-units, which doesn't install via pip unless you have `udunits` installed (`brew install udunits && pip install cf_units`). It was a bit surprising to see it wasn't pure Python...

**Comment by ZLLentz** [comment]
That's odd. I'm happy to find a more portable source for unit conversions, I just picked the first one I found that was acceptably feature-rich. pcdsdevices only uses it for laser time delay stage conversions in a generic sense so you can convert a mm stage to ns delay, or to a fs delay, or to a ms delay... or you can use a stage with units um. I didn't want to rewrite the mapping of standard units.
