### ISSUE TITLE
pcdsdevices/signal.py import can interfere with normal signal module

### ISSUE THREAD

**Issue by ZLLentz** [pcdshub/pcdsdevices#347]
## Expected Behavior

Normal imports should be possible when running code while inside `pcdsdevices` folder to avoid confusion and lost time from pcds engineers.

## Current Behavior

Any code that imports the `signal` module (or that imports something that imports the `signal` module) breaks horribly and incomprehensibly if the current working directory is inside the `pcdsdevices` folder, and sometimes if the file being run is inside that folder (e.g. as a quick test script)

## Possible Solution

Rename the file at our next major version bump?
Or maybe add `from signal import *` inside `pcdsdevices/signal.py`?
Both of those sound bad...

## Steps to Reproduce (for bugs)

1. cd `pcdsdevices/pcdsdevices`
2. Open the python interpreter
3. run python code that relies on the signal module, for example `import asyncio`

## Context

@ZryletTC came me today with a few incomprehensible python bugs and they ended up being this or various forms of this after we spent some time looking at it. This has also come up in the past and I expect it to come up again in the future.

**Comment by klauer** [comment]
You could do something weird like check the current working directory on import of `pcdsdevices.signal` and raise in that case.

I _personally_ don't think this is something that needs fixing on our end - but rather use it as a good teaching example of "where you run stuff matters in Python".

**Comment by ZLLentz** [comment]
I agree that this isn't a bug that needs fixing in the sense that the library isn't broken, but I suspect that doing something will save time in the long run since this has happened a few times.

**Comment by klauer** [comment]
🤷‍♂ OK, how about using any of the following:
* `__name__` (or `__spec__.name`) will show `pcdsdevices.signal` if imported properly, but `signal` otherwise.
* `__package__` will be `None` if imported from the current directory
* There some other stuff in `__loader__`

**Comment by ZLLentz** [comment]
Those are all much better than my awful solution up top
