### ISSUE TITLE
Device Load Issues

### ISSUE THREAD

**Issue by ZLLentz** [pcdshub/pcdsdevices#358]
## Expected Behavior

Disconnected devices instantiate quickly and fail to connect in the background.

## Current Behavior

Disconnected devices have awful behavior with being instantiated on `ophyd=1.3.3` and latest pyepics. They stall for long periods of time.

Unfortuntately, some of our devices (at minimum, `PCDSMotorBase`) fail in `ophyd=1.4.0rc4` because lines like https://github.com/pcdshub/pcdsdevices/blob/89194c33bf73ac5bdac4da48b722c0a6b5d5b5c9/pcdsdevices/epics_motor.py#L183 are not allowed any more (attribute not found error on `self.motor_spg`)

## Possible Solution

Make it work with the ophyd rc candidate and pin `ophyd >= 1.4.0` in the dependencies

**Comment by klauer** [comment]
The failure in 1.4rc seems like an ophyd bug?

**Comment by ZLLentz** [comment]
It certainly could be an ophyd bug, I assumed it was an api change

**Comment by klauer** [comment]
https://github.com/bluesky/ophyd/blob/db8b09d134ba7a0158cb3591779ec8b34341f707/ophyd/device.py#L527-L534
