### ISSUE TITLE
Investigate __new__ override behavior in PytmcSignal and in general

### ISSUE THREAD

**Issue by ZLLentz** [pcdshub/pcdsdevices#372]
Surely the way it's being handled here isn't quite right, despite producing the desired results:
https://github.com/pcdshub/pcdsdevices/blob/f102f9457ca1d2cb5459fe475e89c6d88c96e6d7/pcdsdevices/signal.py#L34-L42

related to #365 

I think this should be the desired way to implement factory classes if it always works and there is a clean/proper way to implement it since it respects inheritance/`isinstance` in clean ways.

If there is no clean way to do this, `PytmcSignal` should be downgraded to a factory function and the corresponding `isinstance` tests should be removed.

**Comment by klauer** [comment]
I think it works quite well and (in my opinion) no further work is really necessary here.

**Comment by ZLLentz** [comment]
Okay, let's close this issue and only open a new one in the case of some discovered issue
