### ISSUE TITLE
ENH: Access to epics reset PV for motion axes

### ISSUE THREAD

**Issue by jsheppard95** [pcdshub/pcdsdevices#391]
`lcls-twincat-motion` defines the PV `:PLC:bReset` for motor records created from a `DUT_MotionStage` using `pytmc`. It would be nice to have access to this PV from a motor screen, i.e the screens produced from `ophyd` devices whose classes inherit from `pcdsdevices.epics_motor.BeckhoffAxis`. Writing to this variable is necessary to clear any axis error and resume motion through epics.

**Comment by jsheppard95** [comment]
Found that component `pcdsdevices.BeckhoffAxis.plc` is using `pcdsdevices.BeckhoffAxisPLC` which has component `cmd_err_reset` that writes to the relevant PV. This component has `kind='omitted'`,  meaning we likely just need to change this to `kind=config`

**Comment by jsheppard95** [comment]
Working in PR #392

**Comment by ZLLentz** [comment]
closed by #392
