### ISSUE TITLE
ENH: Add spherical coordinate support

### ISSUE THREAD

**Issue by ZryletTC** [pcdshub/pcdsdevices#409]
## Expected Behavior
Kappa supports operation in terms of spherical coordinates.

## Current Behavior
Right now, Kappa is only set up as a simple collection of IMS components.

## Possible Solution
There's code from old python to support transformation between spherical coordinates and native Kappa coordinates at: /reg/g/pcds/pyps/xpp/dev/xpp/xppkappa.py

## Context
The Kappa stage is used on the goniometer in XPP.

**Comment by ZLLentz** [comment]
This should be pretty easy to implement as a `PsuedoMotor`

**Comment by ZLLentz** [comment]
https://github.com/pcdshub/pcdsdevices/blob/5927018c9dcfb41eecbd2bbb236720822060402d/pcdsdevices/gon.py#L291

**Comment by klauer** [comment]
https://github.com/pcdshub/typhos/blob/2331e1c5670514d1617d21a36adc499a0488fd44/typhos/cli.py#L226
