### ISSUE TITLE
m2r is broken

### ISSUE THREAD

**Issue by ZryletTC** [pcdshub/pcdsdevices#410]
Docs aren't building because `m2r` is stale and fallen behind compatibility with the `sphinx` API.

Possible solutions:
- Could be fixed by [`m2r`#55](https://github.com/miyakogi/m2r/pull/55)
- If desired, can be bypassed for now by pinning `sphinx<3.0.0` or specifying [the hotfix branch of `m2r`](https://github.com/CrossNox/m2r)
- Realistically, that PR will never be merged as the repo has been inactive since 2018 so a better course of action would probably be to drop `m2r` and switch to `recommonmark` [as others are doing](https://github.com/sphinx-doc/sphinx/issues/7420)

_Originally posted by @ZryletTC in https://github.com/pcdshub/pcdsdevices/pull/400#issuecomment-611848170_

**Comment by ZLLentz** [comment]
I heard murmurs of sphinx making incompatible changes... My vote is always to either drop the dependency and do the docs a different way or to switch to a maintained package.

**Comment by klauer** [comment]
We use `recommonmark` in pytmc and have it suggested in the ci-helpers module. I don't recall it having ever gotten in the way.
