### ISSUE TITLE
Minimal Area Detector Setup for Sub-Devices

### ISSUE THREAD

**Issue by ZLLentz** [pcdshub/pcdsdevices#421]
Right now, our area detector setup has everything and also the kitchen sink. This is great when you're configuring an area detector on its own, but it gets out of hand when dealing with so many signals as a sub-device on something that moves, etc. I just want to start acquisition! Or check the frame rate! Or see the image!

This mainly applies when working interactively through `IPython` or via `typhos`. The `typhos` device for the area detector as-is has a scroll bar a mile long.

I want to create a minimal area detector (`PCDSEmbeddedDetector`?) setup that only has the most-used signals and features, and use it as the attachment for things like PPM and PIM. Then perhaps add some options to instantiate a fully-populated object if it is needed.

**Comment by ZLLentz** [comment]
I spent today trying to implement this ahead of the Friday re-commissioning of the PPMs, but I've hit repeated snags. I do have a somewhat working branch of this, but I'm not satisfied with it because there is a desync between what is seen for read/config in ipython and what is seen in typhos. Customizing which signals are hinted/read/config/omitted is currently a chore in `ophyd` regardless, the only solution seems to be to subclass and override every component, or pass in `read_attrs`, `config_attrs` which doesn't seem to work for `typhos` (not that I like that API anyway). I'm close to breaking and making a utility for this, but it may be better to contribute to the "kind view" idea upstream.

**Comment by klauer** [comment]
I haven't started on the view/overlay idea for ophyd (nor do I have any immediate plans to) so if you have interest, by all means give it a go. It should turn out to be a fun, though perhaps not so easy, exercise in magical Python class-writing.
