### ISSUE TITLE
Many Tests Fail with Latest Ophyd

### ISSUE THREAD

**Issue by ZLLentz** [pcdshub/pcdsdevices#425]
## Expected Behavior

No regressions

## Current Behavior

Explosions

## Steps to Reproduce (for bugs)

1. Update to ophyd=1.4.1
2. run the tests

## Context

Travis is still running the 1.4.0rc4 build and passing, but locally with ophyd 1.4.1 many tests don't pass. Locally with ophyd 1.4.0rc4 every tests passes.

**Comment by ZryletTC** [comment]
Just the disconnected tests or others too?

**Comment by ZLLentz** [comment]
I was running while testing other things and did not take note of exactly what was failing, just that it was related to "things I am not working on".

**Comment by ZLLentz** [comment]
I'm going to investigate this today because it might indicate an API change that needs to be adjusted for.
