### ISSUE TITLE
Add confluence links in existing Device classes + require for all future devices

### ISSUE THREAD

**Issue by klauer** [pcdshub/pcdsdevices#431]
Need to decide on where this goes - class attribute, numpydoc-parseable docstring, or elsewhere?

https://github.com/pcdshub/typhos/issues/114

**Comment by ZryletTC** [comment]
Links to confluence or from confluence to the class documentation?

**Comment by hhslepicka** [comment]
Links so we can get to the confluence page for a device.

**Comment by klauer** [comment]
Clarified the title - sorry 'bout that.

It's also possible we could do this in such a way that we redirect to the correct page from something like this:

https://confluence.slac.stanford.edu/display/PCDS/pcdsdevices.pump.TurboPump -> redirects to useful page or lists possible relevant pages?

**Comment by hhslepicka** [comment]
That is a great idea! I like it!

**Comment by klauer** [comment]
Any further thoughts about this? Management is hoping for a feature like this in the not-too-distant future.

A bit more brainstorming:
1. Use happi to auto-generate main pages
2. Top-level autogenerated page `pcdsdevices.pump.TurboPump` could contain subpages of all instances of `TurboPump`; top-level pages should not be modified by users to avoid being overwritten
3. Each autogenerated page could [include](https://confluence.atlassian.com/conf74/include-page-macro-1003128857.html) a stub page `pcdsdevices.pump.TurboPump - Notes` which should be user editable and customizable
4. More specific pages with only one instance (as in `class AT1K4(...)`) may still follow the above, but may be improved upon somehow?

Additional happi metadata could customize the generated pages, or the linked page from the typhos screens.
