### ISSUE TITLE
python 3.8 travis almost works

### ISSUE THREAD

**Issue by ZLLentz** [pcdshub/pcdsdevices#487]
Locally, testing the latest conda-forge with python 3.8 worked 100% on all unit tests.

Travis fails here now:

```
conda install python=$TRAVIS_PYTHON_VERSION conda-build=3.12.0

UnsatisfiableError: The following specifications were found to be incompatible with a past
explicit spec that is not an explicit spec in this operation (conda):
  - conda-build=3.12.0 -> conda[version='>=4.3']
```

We put the conda-build pin in to fix a weird issue, but it might be time to take off the band-aid

**Comment by klauer** [comment]
So close...

**Comment by klauer** [comment]
_It does work_ with the new shared CI scripts. e.g. https://github.com/pcdshub/pcdsdevices/pull/596/checks?check_run_id=1194664699
