### ISSUE TITLE
PVPositioner[Comparator] based on CCMMotor implementation

### ISSUE THREAD

**Issue by klauer** [pcdshub/pcdsdevices#498]
An idea that we could generalize and re-use this PVPositioner class from https://github.com/pcdshub/pcdsdevices/blob/a5e803867bfb3fa365d499a6b4aa23c29a9aa4a9/pcdsdevices/ccm.py#L30-L73

Requiring either atol or a callable that takes in setpoint/readback or something?

**Comment by ZLLentz** [comment]
`np.isclose` also takes an `rtol` parameter. It may be simplest to just have the user pass in a callable that returns a bool.

Some name choices:
`PVPositionerComparator`
`PVPostionerNoDone`
`PVPositionerIsClose`
`PVPositionerAtPos`

**Comment by klauer** [comment]
I like the `IsClose` one if we bake in the `np.isclose` call. If we make it with a `callable`, then perhaps comparator would be better? 🤷‍♂️
