### ISSUE TITLE
informative Status printout

### ISSUE THREAD

**Issue by silkenelson** [pcdshub/pcdsdevices#502]
**Feature Request**

```
XPP NEW In [3]: att
XPP NEW Out[3]: 
filter# |0|1|2|3|4|5|6|7|8|9|
 OUT    | | | | |X|X|X|X|X|X|
 IN     |X|X|X|X| | | | | | |
Transmission for 1st harmonic (E=9.83 keV): 9.528e-02
Transmission for 3rd harmonic (E=29.49 keV): 9.101e-01

XPP NEW In [5]: ipm2.ty
XPP NEW Out[5]: 
ipm2_yt
	pv XPP:SB2:MMS:03
	current position (user,dial): 30.498047,-30.498047
	user limits      (low,high) : -200.000000,200.000000
	preset position             : reflaser_beamline_position
```

**Existing Alternatives**
```
In [1]: xpp.attenuator                                                                           
Out[1]: Attenuator10(XPP:ATT, name=xpp_attenuator)

In [4]: ipm2.target.motor                                                                        
Out[4]: IMS(XPP:SB2:IPM:TARGET:MOTOR, name=xpp_sb2_ipm_target_motor)
```

**Context**
Want more information easily available.

**Comment by ZLLentz** [comment]
The first pass at this will be using the special `_repr_pretty_` method to define pretty-printing behavior for various device objects. This is used in the `ipython` renderer to decide how to show objects when returned in the terminal. When including devices in strings, `repr` or `str` will be used instead depending on how the string is formatted, which is the desired behavior.

The only qualms I have about this method is that we're taking over what pretty printing means, so if someone tries to pretty print these devices later they won't be super enthused by the results. But this is a good first step and will result in fewer issues than simply overriding `__str__` and `__repr__` like before.

It should also be possible to customize the `ipython` renderers to avoid overloading pretty print, but I'd rather not spend time on that until it is demonstrated to be an issue.
