### ISSUE TITLE
Add motor presets

### ISSUE THREAD

**Issue by ZryletTC** [pcdshub/pcdsdevices#504]
Matthieu has requested motor presets as they existed in the old python.

**Comment by ZLLentz** [comment]
This needs more explanation. Motor presets exist in the new python.

**Comment by ZryletTC** [comment]
Oops, I didn't realize.
He seemed to believe they did not exist so yes, probably too hard to find. We need to work on the auto-complete :/

**Comment by ZLLentz** [comment]
Right, that makes sense.

**Comment by ZLLentz** [comment]
I have to wonder if the autocompletion filters need a full rework at this point

**Comment by ZryletTC** [comment]
I think so. I'll start a discussion offline after talking with some scientists.
