### ISSUE TITLE
PV put during LookupTablePositioner init

### ISSUE THREAD

**Issue by ZLLentz** [pcdshub/pcdsdevices#530]
## Expected Behavior

No puts

## Current Behavior

Can do EPICS puts, which either succeed and change the beamline or fail and cause the object to not be created.
https://github.com/pcdshub/pcdsdevices/blob/b59c9ade3f4e5007851528c54c7be942aeefdcd2/pcdsdevices/pseudopos.py#L240
Setting a limits attribute on a positioner is not safe as it can be linked to a PV.

**Comment by klauer** [comment]
😮 which devices have `limits` setters that update PVs? I had done a preliminary search but came up with nothing...

**Comment by ZLLentz** [comment]
lxt, for starters! Let me look a little bit into why

**Comment by ZLLentz** [comment]
culprit identified
https://github.com/pcdshub/pcdsdevices/blob/b59c9ade3f4e5007851528c54c7be942aeefdcd2/pcdsdevices/epics_motor.py#L63-L89

**Comment by ZLLentz** [comment]
obligatory "we did this to ourselves"

In general I think it is bad practice to set these via attributes

**Comment by klauer** [comment]
Gotcha. Those properties hid the functionality in my clearly insufficient research...

**Comment by klauer** [comment]
Not sure of the appropriate fix here just yet, other than just a hotfix to skip setting the limits for now.

**Comment by ZLLentz** [comment]
I think I may propose a second PR that makes the limits attributes not settable, as they aren't in the parent EpicsMotor classes and I'd prefer some consistency.

**Comment by klauer** [comment]
Do you think there's no value in ophyd-imposed limits, separate from the control system's limits? That was my intent of setting `.limits`, in any case, for this positioner.

**Comment by ZLLentz** [comment]
I do think that concept has value, and that it would not be difficult to implement.

**Comment by ZLLentz** [comment]
If the limits attr is settable, it surely should be setting a local ophyd limit.

**Comment by klauer** [comment]
OK, in that case, should the pcdsdevices-flavor `EpicsMotor` limits setter just be adjusted to tweak `_limits` like the pseudo singles do?

I think, then, so long as we're using our pcdsdevice's version in these scenarios, the limits setting functionality could even be defaulted to true. Or back to what it was pre-PR.

**Comment by ZLLentz** [comment]
In some sense, the only motor classes with this issue are ours. So if we fix our motor classes, we don't need to adjust the LookupTablePositioner.

**Comment by klauer** [comment]
Cool - we appear to be in agreement. I'll remove the functionality from my PR, but retain the limits tests as they're a good check.

Do you want to do the `EpicsMotor` changes?

**Comment by ZLLentz** [comment]
Sure, I'll slap a change in `EpicsMotor` once I exhaust my notification/review queue

**Comment by klauer** [comment]
Closed by #536
