### ISSUE TITLE
LXT has no hinted signals, preventing LiveTable

### ISSUE THREAD

**Issue by ZLLentz** [pcdshub/pcdsdevices#532]
## Expected Behavior

Hinted readback

## Current Behavior

No hints = LiveTable crash

## Possible Solution

IDK, livetable doesn't display 1e-9 very well anyway.
We used the hidden signal in the xcs beamline because the units were better for the table

**Comment by klauer** [comment]
Adding kinds now. I'll leave the hidden signal as-is, but that can be tweaked by the user (or we can revisit, I suppose).

**Comment by ZLLentz** [comment]
I think we may also need to roll a LiveTable that is aware of when it needs to display in exponential form

**Comment by klauer** [comment]
Checking for 'really small values to show in exponential format' can lead to things like this in a scan:
`Position: 1.0342e-64`
`Position: 1000.0`
`Position: 1.0325e-63`

With that in mind, perhaps this could be the first non-GUI consumer of `variety` metadata. We'd at least be then able to specify our 'display format' in the scenarios in which it's desirable.

**Comment by ZLLentz** [comment]
I agree that a LiveTable that was variety-aware would be an excellent addition. Is this another thing to consider for `nabs`?

**Comment by klauer** [comment]
`nabs` seems a good spot for it 👍
