### ISSUE TITLE
BeamEnergyRequest should not have any links to the actual beam Energy

### ISSUE THREAD

**Issue by ZLLentz** [pcdshub/pcdsdevices#546]
This is causing issues with waiting, unexpected move requests, etc.

From Silke:

"I'm not sure we have a super reliable energy we get from AD: it varies from shot-to-shot. And I'm not sure of the PMPS number takes the vernier into account"

**Comment by klauer** [comment]
PMPS has no knowledge of the vernier (neither do I, for that matter...).
