### ISSUE TITLE
`DelayNewport` unused in device_config / pcdsdevices

### ISSUE THREAD

**Issue by klauer** [pcdshub/pcdsdevices#548]
Maybe mark for removal?

https://github.com/pcdshub/pcdsdevices/blob/dc9237ce539da7de76bf31371652b9506ff3ef99/pcdsdevices/epics_motor.py#L438-L439

**Comment by ZLLentz** [comment]
Used locally in xcs's beamline file right now

**Comment by ZryletTC** [comment]
Please don't remove!

**Comment by klauer** [comment]
Gotcha. Nothing to see here.
