### ISSUE TITLE
Add lxt_new (delayNew)

### ISSUE THREAD

**Issue by klauer** [pcdshub/pcdsdevices#556]
Not yet requested, but in the same group of virtual motors. Creating issue to aggregate information for now.

Notes
------
* `lxt_new`, a virtual motor based on `delayNew`
* Delay stage `xppDelayNew`/`xcsDelayNew` (`delayNew`), based on `las_delayNew`
    * XCS: `XCS:LAS:MMN:03`
    * XPP: `XPP:LAS:MMN:04`

**Comment by ZLLentz** [comment]
Is this not the existing `lxt_fast`? I think we renamed it from new to fast for clarity.

From xcs's beamline file:
```
    lxt_fast = Newport('XCS:LAS:MMN:03', name='lxt_fast')
    lxt_fast_s = DelayNewport('XCS:LAS:MMN:03', name='lxt_fast_s')
```

**Comment by klauer** [comment]
Then requested and implemented it is 👍
