### ISSUE TITLE
Relative moves fail in our pseudopositioners due to non-numeric position

### ISSUE THREAD

**Issue by ZLLentz** [pcdshub/pcdsdevices#557]
## Expected Behavior

Should be able to use mvr, umvr

## Current Behavior

Pseudopositioner tuple is returned from the position attribute, which cannot be added or subtracted to like we do in the relative moves.

## Possible Solution

- Patch the `position` attribute to return the first element of the pseudoposition
- Or patch the `wm` method to return the first element
- Or patch `mvr` and `umvr` to be pseudopositioner-aware

**Comment by ZLLentz** [comment]
I am opting to try to knock this out via changing the wm command. I'm not so sure changing the behavior of the position attribute is a good idea, nor am I sure where I should be changing it.

**Comment by klauer** [comment]
I modified `wm` for `LaserEnergyPositioner` - would you mind removing that fix as part of your PR?
