### ISSUE TITLE
Allow offsets/zeroing in delay stage class

### ISSUE THREAD

**Issue by ZLLentz** [pcdshub/pcdsdevices#568]
## Expected Behavior

Have a user-configurable offset in the delay stage class

## Current Behavior

We just multiply the real motor number to get the time number

**Comment by ZryletTC** [comment]
The motors under the delay objects have offsets. That's worked for me up until now but you're probably right that people will want it on the delay object itself.

**Comment by ZLLentz** [comment]
This came from a slack post
