### ISSUE TITLE
Be lens class documentation, etc.

### ISSUE THREAD

**Issue by ZLLentz** [pcdshub/pcdsdevices#577]
Original card:
- combined motor working in spot-size as position
- code believed to be present, needs name to be known (potentially aliases), test functionality

My take:
- Better documentation on how to use `LensStack.calib_z` and `LensStack.beam_size`
- Testing with real hardware
- Consider changing API to be more like old python
- Consider refactoring code to make it easier to read
- Also look at #541

**Comment by ZLLentz** [comment]
Also teach how to use

**Comment by cristinasewell** [comment]
@ZLLentz - regarding the `Consider changing API to be more like old python` suggestion above, what old code used to handle this class, is it this class here?:
https://github.com/pcdshub/old-hutch-configs/blob/18c7769d66a647ab558ad7ebc34d019fc98fbf48/xpp/blinst/crl.py#L28

**Comment by ZLLentz** [comment]
Yes, that's the old class.

Note that most of the method names there are not pep-8 compliant... so I'm not super keen on copying the old API exactly.

**Comment by cristinasewell** [comment]
> Yes, that's the old class.
> 
> Note that most of the method names there are not pep-8 compliant... so I'm not super keen on copying the old API exactly.

Ok that sounds good, but the main thing here is that we want to bring back some of these functions that are missing correct? 
Like the `planSet` and maybe others

**Comment by silkenelson** [comment]
You can check with Matt and maybe also Roberto: we need ‘planSet’ and this needs to be able to access standard XPP/XCS/MEC configurations. This does not need to be necessarily implemented in thee BeLens class, only in the calc might be ok. I would let the scientists decide.

Mainly we need to make sure that we have a functioning “focal-size” motor for each pack that can be calibrated at the beginning of the experiments which ideally saved these focus size to a PV. The scientists need to understand how to use it. If we want to modify function names to make the them compliant, that is not a deal breaker, just keep them in the loop & document.

**Comment by silkenelson** [comment]
I found the old Be Lens code & files. We do carry information for three sets around. For aligning a set, we explicitly say which set we are on 0/1/2 and save the data in a json file. When this code gets used to move to a given focus, the states are used (as they should be). I would think that the lens sets should try to read a file in the <hutch>opr/experiments/directory and write the calibration-data there as well. We would need to make it a policy to copy these files. Better ideas are welcome.

XPP NEW In [2]: crl._CRLConfigFile
XPP NEW Out[2]: '/reg/neh/operator/xppopr/xpppython_files/Be_lens_sets/current_set'

XPP NEW In [3]: crl._calibfile
XPP NEW Out[3]: '/reg/neh/operator/xppopr/xpppython_files/Be_lens_calib/beam_trajectory.json'
