### ISSUE TITLE
Move interface: consider catching limit-related exceptions to not overwhelm the user with traceback messages

### ISSUE THREAD

**Issue by klauer** [pcdshub/pcdsdevices#591]

**Comment by klauer** [comment]
Alternative: set `%xmode` based on engineering mode?

**Comment by ZLLentz** [comment]
`%xmode` sounds like a great idea, though I was also :+1: on making exceptions more user-friendly

**Comment by klauer** [comment]
Considering everyone appears in favor of `%xmode` - maybe instead of using it as an alternative, we should do both? That is to say, noisy limit exceptions seem unnecessary regardless of engineering mode, I think.

**Comment by ZryletTC** [comment]
Both is good. For the xmode part, possible solution is to add the following to `interface.set_engineering_mode`
```
from IPython import get_ipython
ip = get_ipython()
if expert:
ip.InteractiveTB.set_mode(mode="Verbose")
else:
ip.InteractiveTB.set_mode(mode="Minimal")
```
where it would be good to add an underscore to `engineering_mode` to make it more "private"

Might include this in some sort of small fixes PR. Better ideas very welcome though!

**Comment by klauer** [comment]
Looks like we were thinking about the same issue at the same time, @ZryletTC. I moved the `%xmode` stuff over to hutch-python - feel free to take it over there, as I've only messed with the pcdsdevices side of things as of yet.

**Comment by ZryletTC** [comment]
Haha yeah, I guess so. I'm not sure it should be a hutch-python thing because engineering-mode is controlled by the pcdsdevices interface.

**Comment by klauer** [comment]
It makes perfect sense for engineering mode to control tab completion for devices it supplies.
On the other hand (in my opinion), it doesn't make sense for a package offering devices to affect how all tracebacks are formatted for _everything_ in IPython. 

As hutch-python is our user-facing IPython-based CLI, in a way, traceback formatting settings belong there.

**Comment by ZLLentz** [comment]
Hmm, it seems like the "engineering mode" settings live in the wrong repo altogether (though it's fine if individual repos have engineering mode switches that are local to the code they control)

**Comment by klauer** [comment]
Yeah, I think you're probably right @ZLLentz. Say our libraries were supposed to play nice and share/use this setting, where would it go? `IPython.user_ns`? `pcdsdevices` doesn't depend on IPython, hmm...

**Comment by ZLLentz** [comment]
Abstractly, we'd have most repos with an engineering mode feature handle their own settings, and we'd do one of the following or something similar:
1. Make top-level applications like `hutch-python` supply a switch that fans out to all of them (e.g. pass its own switch into the user_ns)
2. Set a global variable in the most common/least-dependency repo (`pcdsutils`?) that would then be checked by every repo that implements an engineering mode setting. Supply functions that set/get this global.

**Comment by ZryletTC** [comment]
Yes, I totally agree

**Comment by ZLLentz** [comment]
I'm leaning towards a pcdsutils switch since it sounds really easy to implement/use

**Comment by klauer** [comment]
I'm on board with a `pcdsutils` option. Can you think of any other runtime-level configuration that would be reasonable to provide there? Just thinking it may drive the direction of the new API.

**Comment by ZLLentz** [comment]
Most repos already handle their own configuration pretty adequately. The category we're considering here is settings that are "big switch" kinds of settings that need to be able to activate/deactivate at the user's direction that we can group across repos and want to be able to set/reset the group of them in a consistent way.

Logging verbosity comes to mind, as does debug-level things like profiling. Simulation mode maybe?

**Comment by klauer** [comment]
Nice concise description. All of your provided examples seem like good candidates for inclusion at some point.  👍 

No others coming to my mind at the moment...
