### ISSUE TITLE
Von Hamos Motion class

### ISSUE THREAD

**Issue by jsheppard95** [pcdshub/pcdsdevices#636]
Need a motion class for the Von Hamos Spectrometer. As a first pass, it will just contain the Y axis motor needed for XPP's LV68 experiment.

**Comment by ZryletTC** [comment]
What motor names and types does the full class need?

**Comment by jsheppard95** [comment]
Oh I made this Issue so I could refer to it in the release notes of this PR: https://github.com/pcdshub/pcdsdevices/pull/635 which just contains the class `vonhamos_motion.VonHamos`. So far it just contains the single Beckhoff Y axis, but I'm now thinking this is overkill and really I should just create a `happi` entry for this motor and set the class as `epics_motor.BeckhoffAxis`, at least for the LV68 experiment. I could then revisit this when the rest of the VonHamos axes are converted to Beckhoff.

**Comment by ZryletTC** [comment]
Good plan 👍

**Comment by ZLLentz** [comment]
I'm going to put Jackson's name on the assignment for this issue so it's clear that it is a self-issue/documentation and not a request
