### ISSUE TITLE
Add import tests for all modules

### ISSUE THREAD

**Issue by ZLLentz** [pcdshub/pcdsdevices#647]
## Expected Behavior

Test that every class's class definition works on import. For bonus points, test that every class can be instantiated.

## Current Behavior

https://github.com/pcdshub/pcdsdevices/pull/646#issuecomment-716656907

## Possible Solution

Example: https://github.com/pcdshub/pcdsdevices/blob/03a1dc2cdd08b8a39198e4bed9834b436c445732/tests/test_wfs.py#L1-L13

## Context

Can catch bugs that are easy to miss if we're going fast

**Comment by klauer** [comment]
Top-level modules actually do not have this issue. I think the issue was that this happened in a submodule of pcdsdevices.

Why? I did a quick `echo 'garbage string' > pcdsdevices/foobar.py` and `test_interface` fails:

```
================================================================ ERRORS =================================================================
_______________________________________________ ERROR collecting tests/test_interface.py ________________________________________________
test_interface.py:219: in <module>
    for cls in conftest.find_all_device_classes()
conftest.py:103: in find_all_device_classes
    __import__(f'{pkgname}.{module}')
../pcdsdevices/foobar.py:1: in <module>
    jasldfkjalksdjfaoi
E   NameError: name 'jasldfkjalksdjfaoi' is not defined
```

**Comment by ZLLentz** [comment]
I don't see how this could happen then, since the `find_all_device_classes` mechanism looks like it is iterating properly through submodules

**Comment by klauer** [comment]
We now do best-effort instantiation of all device classes found in pcdsdevices, including those in sub-packages.

I think this is good enough, but feel free to re-open if you don't.
