### ISSUE TITLE
Custom Status Prints for PsuedoPositioners

### ISSUE THREAD

**Issue by ZLLentz** [pcdshub/pcdsdevices#671]
## Expected Behavior
```
In[1]: ccm.E
Out[1]:
Virtual Motor CCM Photon Energy   XCS:MON …(user pV?)
current position (user, dial): 7.002, 7.002n [eV]
user limits (low, high): 5.000, 15.000  [eV]
preset position: xxxxxx


In[2]: m.lxt
Out[2]:
Virtual Motor Laser X-ray Timing   [LXT USER PV?]
current position (user, dial) 2.341 [ps], 4.321452 [ns]
```

## Context

https://docs.google.com/document/d/1dmalnT4xLPWoJESsMHTxzIyzlGCBgTQjGNYwDhU-pzo/edit#heading=h.ylcn31lb55xr

**Comment by cristinasewell** [comment]
Does the nice description `CCM Photon Energy`, `Laser X-ray Timing` exist already in a `.DESC` field? I'd like to test with these examples above but can't figure out the PVs they used or the happi entries that they loaded

**Comment by ZLLentz** [comment]
I think they definitely do not already exist in a DESC field... This may be related to #667.

But for these perhaps we can assign a name on a per-class basis?
ccm.E is this component: https://github.com/pcdshub/pcdsdevices/blob/19ab81228f53a1b41f22b3e78e95abb0d9a88977/pcdsdevices/ccm.py#L76
 which always is a "CCM Photon Energy" motor, for example, for both real devices that are CCMs.

But now this issue becomes an exercise in hunting down where exactly each psuedosingle or pseudopositioner is defined and what it is used for...

I think this one is the lxt: https://github.com/pcdshub/pcdsdevices/blob/19ab81228f53a1b41f22b3e78e95abb0d9a88977/pcdsdevices/lxe.py#L250

**Comment by ZLLentz** [comment]
Maybe? Or we can hard-code these two cases for now and consider the general case later.

**Comment by cristinasewell** [comment]
Ok sounds good. 

So there are a couple of things here that I need to do if I understand correctly?:
- override `format_status_info` for `PseudoSingleInterface` in `pcdsdevices.pseudopos.py` and override the `format_status_info` for classes that inherit from `PVPositioner`?

If so, for the classes that are PVPositioners I can have a name for the verbose description and use that.
For the `PseudoSingleInterface` components though,  e.g.:` energy = Cpt(PseudoSingleInterface, egu='keV', kind='hinted',` - how would I get a verbose name for this guy, this component is part of a `CCM` device

Is there a way we can get the doc value of the component somehow? or is this not the right approach?
```
    energy = Cpt(PseudoSingleInterface, egu='keV', kind='hinted',
                 limits=(4, 25), doc='CCM Photon Energy')
```
Overriding the `format_status_info` for `PseudoSingleInterface` would give me something like this for example:

```
In [1]: xcs_ccm.calc.energy
Out[1]:
Virtual Motor XCS:MON:MPZ:01:energy
Current position (user, dial): 8.630370238006924, None []
User limits (low, high): 4, 25 []
Preset position: Unknown
```

**Comment by ZLLentz** [comment]
I think including the verbose name in the Component is a really good idea- I'm not sure `doc` is the right tag for that, but I'm not sure we have anything better? I'd say go for it, it will immediately apply to all the pseudo single axes which has a ton of utility. The only other option I can think of is subclassing `PseudoSingleInterface`, overriding `format_status_info`, and changing the component to use your new subclass, but this would need to be repeated on every instance! Very annoying, much better to use `doc`. Maybe later we figure out a new kwarg for it so you can have all three: a name, a verbose name, and a long doc?

**Comment by cristinasewell** [comment]
Can anybody provide me with some Virtual Motor PVs for this: `XCS:MON …(user pV?)` and  `[LXT USER PV?]` 

Is this a good one for the energy?
`XCS:MON:MPZ:01`

and this one for LXT?
`XPP:USER:LXT`

If so, I'm still struggling understanding what the scientists are using to get the Dial Position from.??

**Comment by klauer** [comment]
The `doc` usage seems great to me. If you need something really verbose there, perhaps just by convention it could be:
```
first line is descriptive name [units]
second
and third+ lines: verbose information
```
Such that `verbose_name = doc.split('\n')[0]`

The virtual motor PVs are from notepad IOCs - the ones you listed are from the older style (which is still in heaviest use at this point). Recently, I added functionality to keep setpoint and readback PVs up-to-date automatically by way of `PseudoSingleInterface` (those `:OphydSetpoint` and `:OphydReadback` components). Not sure where that fits in for what you're asking, though.

**Comment by silkenelson** [comment]
XCS:MON:MPZ:01 is the actual underlying motor for the CCM (sort of, this motor is not actually a motor record, this motor is made of a few separate records, combined in python to work more like a 'normal' motor). XPP:USER:LXT is a notepad PV we used in the past to write the 'pseudo-position' to, but I do not know what the new 'lxt' virtual motor is using.

**Comment by ZLLentz** [comment]
I'm not sure where the CCM dial position could ever come from- isn't the whole calculation meaningless if the angle readback isn't properly zeroed? I do note that in the provided example, dial and user positions are exactly the same.

**Comment by silkenelson** [comment]
The also (CCM angle stage) has a PLC program for homing. Unless the scientist don't operate it right, it has an absolute position.

**Comment by ZLLentz** [comment]
In that case, there should be never be any difference in dial vs user position for the CCM Energy PseudoPositioner
