### ISSUE TITLE
Custom Status Print for IPM

### ISSUE THREAD

**Issue by ZLLentz** [pcdshub/pcdsdevices#673]
## Expected Behavior
```
In[1]: ipm2
Out[1]:
XPP SB2 IPM: Target 2 IN [2.0 um Silicon Nitride]
Target Position: 32.015 [mm]
Wave 8 Diode Position (x, y): 0.013, 0.025 [mm]
```
Where exactly to get/store the 2.0 um Silicon Nitride information is an open discussion item.

## Context

https://docs.google.com/document/d/1dmalnT4xLPWoJESsMHTxzIyzlGCBgTQjGNYwDhU-pzo/edit#heading=h.ylcn31lb55xr

**Comment by silkenelson** [comment]
I'm going with the DESC field of one of the TARGET PVs. (the :GO or :SET or _SET field - I'm not sure what is easier to implement in a way where the states&their names get 'auto-discovered')

**Comment by cristinasewell** [comment]
Ok that's good, so I should be able to create a component in `IPMTarget` to get this information from correct?
something like this:
```
target_composition = Cpt(EpicsSignalRO, ':GO.DESC', kind='normal')
```

**Comment by ZLLentz** [comment]
I think that's the correct approach Cristina.

Silke, I think they are all equivalent from the python side- we just need to pick one. It's easy to change our minds later too.

**Comment by ZLLentz** [comment]
Wait, hang on: is there a different composition per state? If so we need to use one of the SET fields probably, and preferably one whose PV names are consistent across all IPMs.

**Comment by silkenelson** [comment]
Yes, each state is a different target with different material/thicknesses. What would be a consistently named PV? When I know, I can have Diling fill out the ones for XPP so that we can test with something that has actual text it in.

**Comment by ZLLentz** [comment]
I did a survey of all the IPMs, they all have PVs like the following that I think are pretty optimal for this:
```
CXI:DG2:IPM:TARGET:TARGET1.DESC
CXI:DG2:IPM:TARGET:TARGET2.DESC
CXI:DG2:IPM:TARGET:TARGET3.DESC
CXI:DG2:IPM:TARGET:TARGET4.DESC
```

**Comment by cristinasewell** [comment]
So I think I'll have to have 4 different components? 

```
target1_composition
target2_com...
target3....
target4...
```
and maybe a method to determine which one is the current one?

I can't think of a more elegant way, because at the time of the Component creation I won't know the target state correct?, so I won't be able to do something like:
```
target_composition = FCtp(EpicsSignalRO, '{self.prefix}:TARGET:TARGET{some_state_value}.DESC', kind='normal')
```

**Comment by ZLLentz** [comment]
I think the `state` signal (as well as the `position` attribute?) tell us which target we're at, and therefore which `.DESC` to check.

**Comment by cristinasewell** [comment]
Yes we can get it from the `state` - but I was wondering if I should create components for the each target composition in the IPMTarget though. 
Or could I do something like this in the `IPMTarget`: ?

```
    def get_composition(self):
        current_state = self.state.get()
        return EpicsSignalRO(f'{self.prefix}:TARGET{current_state}.DESC', name='x').get()
        
```
or is this not very good practice?

**Comment by klauer** [comment]
It is indeed not good practice to create a throwaway `EpicsSignal`. (I haven't followed this conversation closely enough to suggest an alternative though...)

**Comment by cristinasewell** [comment]
> It is indeed not good practice to create a throwaway `EpicsSignal`. (I haven't followed this conversation closely enough to suggest an alternative though...)

Ok thanks for letting me know @klauer

**Comment by ZLLentz** [comment]
I think we need to create 4 components that hold the chosen DESC fields, then pick which one to display (or not to display any) based on the current state.

**Comment by cristinasewell** [comment]
> I think we need to create 4 components that hold the chosen DESC fields, then pick which one to display (or not to display any) based on the current state.

Great, I think my solution in a3a706b would then work - but needs testing.
