### ISSUE TITLE
Add 3rd harmonic to Attenuator status print

### ISSUE THREAD

**Issue by ZLLentz** [pcdshub/pcdsdevices#675]
## Expected Behavior

Include 3rd harmonic:
```
In [1]: att
Out[1]:
XCS Beamline Attenuator on SB2
filter # |0|1|2|3|4|5|6|7|8|9|
 OUT     |X|X|X|X|X|X|X|X|X|X|
 IN      | | | | | | | | | | |
Transmission for 1st harmonic (E=7.92 keV): 1.0000E+00
Transmission for 3rd harmonic (E=23.76 keV): 1.000e+00
```
This might require some reworking of the Att classes so that we don't have separate 1st and 3rd harmonic devices

## Context

https://docs.google.com/document/d/1dmalnT4xLPWoJESsMHTxzIyzlGCBgTQjGNYwDhU-pzo/edit#heading=h.ylcn31lb55xr

**Comment by klauer** [comment]
I was looking to close this issue as the PR was merged, but I noticed this when double-checking:

https://github.com/pcdshub/pcdsdevices/blob/e5cf6f66c9db5d5d32bb4a654f76a74e17f3e5ab/pcdsdevices/attenuator.py#L320-L321

The same variable is used for both transmissions - that can't be right, can it?

**Comment by cristinasewell** [comment]
I don't think this is right, thanks for catching this. 
I think I should be getting the `readback_3rd` value instead?

**Comment by klauer** [comment]
That seems like it could be it, @cristinasewell... Does `caget (that_pv).DESC` tell us anything useful? Failing that, I'd imagine the old EDM screen has a spot for 3rd harmonic transmission that you could check.

**Comment by cristinasewell** [comment]
Ok i'll check this later today and put in a fix for it, thanks @klauer

**Comment by cristinasewell** [comment]
```
caget MFX:ATT:COM:R3_CUR.DESC
MFX:ATT:COM:R3_CUR.DESC        Floor Ratio
```

I think it is this one. Also based on an EDM screen: 
![att](https://user-images.githubusercontent.com/62306310/103740513-352c5880-4fac-11eb-9aaf-7d003539eb0a.PNG)

The third harmonic has this pv:
```
XPP:ATT:COM:R3_CUR
```
which is similar to the one above.

**Comment by klauer** [comment]
Looks like the description is wrong (likely a copy-paste bug when making the EPICS database), but if the screen shows `R3_CUR` that'd be the one 👍
