### ISSUE TITLE
Custom status print for XPP Gon

### ISSUE THREAD

**Issue by ZLLentz** [pcdshub/pcdsdevices#682]
## Expected Behavior
```
In[1]: gon
Out[1]:
XPP Goniometer
H, V: 600.02, 7.2 [mm]
Theta, Pitch, Roll: 0.0022, 0.2321, 0.0025 [deg]
X, Y, Z: 0.0232, 0.2342, 0.2342 [mm]
```

## Context

https://docs.google.com/document/d/1dmalnT4xLPWoJESsMHTxzIyzlGCBgTQjGNYwDhU-pzo/edit#heading=h.ylcn31lb55xr

**Comment by cristinasewell** [comment]
Are `theta`, `pitch` and `roll` related to the Gon `Rotation`, `Tilt`, and `Tip`? respectively?
Or are these separate components?

Also the `X`, `Y` and `Z` - are they additional components that need to be added to the `BaseGon` class?

We have the `XYZStage` wich has the `X,` `Y`, and `Z` - are these the ones we're talking about in the example above?

**Comment by ZryletTC** [comment]
Yes, Theta=Rotation, Pitch=Tilt, Roll=Tip.
And X/Y/Z are from the XYZStage
