### ISSUE TITLE
EpicsMotor Signals Need Metadata

### ISSUE THREAD

**Issue by slactjohnson** [pcdshub/pcdsdevices#695]
## Expected Behavior
Screens generated via Typhos have reasonable looking interfaces, with widgets that make sense visually, as well as with correct units (or no units, when applicable). 

## Current Behavior
Many useful signals in the upstream ophyd.epics_motor.EpicsMotor class are kind='omitted'. This makes them annoying to access from Typhos screens. Things like motor homing should probably at least be kind='config'. 

Also, Ophyd doesn't use our variety package, so there is no metadata helping Typhos figure out what to do with these signals. This causes you get confusing Typhos screens like this:

![image](https://user-images.githubusercontent.com/29102919/98423972-24f80b80-2045-11eb-9a50-14086154c5a4.png)

## Possible Solution
Since upstream ophyd doesn't use our variety metadata, it seems like we need to overwrite these signals in our implementation. Seems like lines like:

```
home_forward =  Cpt(EpicsSignal, '.HOMF', kind='config', doc='Home the stage forward')
set_metadata(home_forward, dict(variety='command-proc', value=1))
```

to EpicsMotorInterface would do the trick for these signals. 

## Steps to Reproduce (for bugs)
Generate a Typhos screen using a device that sub-classes ophyd.epics_motor.EpicsMotor or our EpicsMotorInterface. Example: pcdsdevices.epics_motor.SmarAct. 

## Context
These signals are hidden on the Typhos laser control screens I have generated, so laser scientists weren't sure how to home motors. Once we figured out where the signals were, the screens were confusing. 

## Your Environment
dev_python

**Comment by klauer** [comment]
I'm on board with adding metadata to it to make the auto-generated screens look even a bit better.

The only unfortunate thing is having to copy in all of the components in the subclass just to do it.
While it wouldn't be "proper" to monkeypatch `EpicsMotor` in-place, I think this would work based on how I did `set_metadata`:
```python
set_metadata(EpicsMotor.home_forward, dict(variety='command-proc', value=1))
```

If it does work, it has minimal potential for side-effects, I'd think.

**Comment by ZLLentz** [comment]
I'm happy with what @klauer is suggesting as implementation. In general though we have a hole where it is extremely awkward to overwrite components from the parent class- not just for metadata. I think it's worth thinking about a way to do this explicitly in the child class that doesn't evolve a huge amount of copying and pasting.

**Comment by klauer** [comment]
Completely agreed, @ZLLentz. I think if `Component` supported `__copy__` better, we could use the same pattern you/Teddy did with happi containers (e.g., https://github.com/pcdshub/pcdsdevices/blob/5c1154159f3034a112b92044b1cbd44ba77c0e33/pcdsdevices/happi/containers.py#L32)

**Comment by ZLLentz** [comment]
I'm surprised to hear that the default `__copy__` doesn't work well for `Component` objects. That kind of sucks.

**Comment by klauer** [comment]
It _might_ already, but I have my doubts without looking more closely into that code again.
