### ISSUE TITLE
Tab completion entries are unfiltered when jedi completion is disabled

### ISSUE THREAD

**Issue by klauer** [pcdshub/pcdsdevices#709]
## Expected Behavior
Tab completion should filter undesirable items outside of engineering mode, _regardless of the Jedi configuration_.

## Current Behavior
While engineering mode = `False`, and jedi completion off:
<img width="884" alt="image" src="https://user-images.githubusercontent.com/5139267/99852968-ee3aee80-2b36-11eb-8b64-ec0eb5aff7e1.png">

And yet:
```
In [39]: ', '.join(dir(at2l0))
Out[39]: 'blade_01, blade_02, blade_03, blade_04, blade_05, blade_06, blade_07, blade_08, blade_09, blade_10, blade_11, blade_12, blade_13, blade_14, blade_15, blade_16, blade_17, blade_18, blade_19, calculator, camonitor, check_value, configuration_attrs, configure, connected, describe, egu, get, limits, log, move, moving, mv, mv_ginput, mvr, name, num_in, num_out, position, presets, put, read, read_attrs, settle_time, stage, stop, summary, timeout, trigger, tweak, umv, umvr, unstage, wait_for_connection, wm, wm_update'
```

Re-enabling jedi, we see:
<img width="881" alt="image" src="https://user-images.githubusercontent.com/5139267/99853064-23474100-2b37-11eb-967f-f61351639f6f.png">

(brought to my attention by @ZryletTC, confusing us both)

**Comment by klauer** [comment]
It's still calling `__dir__` on the object, so perhaps it's just including `dir(cls)` as well... (e.g., `dir(AT2L0)` here)

**Comment by klauer** [comment]
Upstream issue: https://github.com/ipython/ipython/issues/8330

They _removed_ `dir(cls)`here, https://github.com/ipython/ipython/pull/8355, then re-added it in https://github.com/ipython/ipython/pull/10046.

As IPython authors appear to think that what we're seeing is "correct", I suppose our possible options are:
* Re-enable Jedi completion
* Monkey-patch IPython to replace `dir2` with `dir` (leaving Jedi off)

**Comment by ZLLentz** [comment]
Ugh what a mess

- We can't re-enable Jedi for tab completion because that slows us down a ton and makes the session unusable
- I think it's ok to monkeypatch out dir2 but it is distasteful and liable to break later

IPython says that modifying `__dir__` should work to customize tab completions in the official docs:
https://ipython.readthedocs.io/en/stable/config/integrating.html#tab-completion

So this is either a bug or a docs error at the base

**Comment by klauer** [comment]
Yeah, those docs sure make it seem like that's how it should be. The new functionality does not appear to be contentious, I'd guess because so many are just using Jedi.

More details:
I stopped digging when I saw: https://github.com/ipython/ipython/pull/10046#issuecomment-281837012 (_"So consistency lean toward ignoring custom __dir__."_)
I should have followed it one step further: https://github.com/ipython/ipython/issues/10349
This last issue appears to be the discussion thread for "we waffled on whether to include `dir(cls), ultimately said leave it in, and opened an issue for future discussion` [nearly 4 years ago].

**Comment by ZLLentz** [comment]
Yeah alright we should just monkeypatch at some level- here or in hutch-python?

**Comment by ZLLentz** [comment]
I suspect Jedi works a lot better when you aren't using a network-based file system, for what it's worth

**Comment by klauer** [comment]
I had already jumped down the rabbit hole by the time I saw this - but I think you'll probably agree that hutch-python seems the right spot for it.
