### ISSUE TITLE
EventSequencer Proc

### ISSUE THREAD

**Issue by ZLLentz** [pcdshub/pcdsdevices#716]
## Expected Behavior

Event Sequencer should apply a new sequence immediately and we should be able to wait on it in a scan

## Current Behavior

Event Sequencer takes up to 5s to apply a new sequence and we don't realize that it hasn't worked
Email from Bruce:
```
It's not well documented, but I found this comment in the db file:
# "Note that $(IOC):$(ID):SEQ only processes upon writing 1 to its PROC field."

Can you try adding a caput  ECS:SYS0:6:SEQ.PROC 1 to your script after it updates the sequence?

I suspect the EVG was written this way so it wouldn't rebuild the sequences as each step is updated.
The 5 second delay comes from the IOC, which monitors each of the sequence steps and
writes 1 to the SEQ.PROC field after 5 seconds of no changes.
```

## Possible Solution

- Write to the PROC field on sequence updates
- Tie some PV to the status object of trigger

## Context

MEC event sequencer swap between scans (scan points?) issues

## Your Environment

Latest

**Comment by slactjohnson** [comment]
Beat me to it. :)

**Comment by slactjohnson** [comment]
@ZLLentz adding the SEQ.PROC line is trivial, but I am a little confused by your comment about the sequencer trigger. Looking at the trigger method, the status object comes after we've already started the sequencer. It seems like we should be verifying that the SEQ record is not actively processing (and therefore re-writing the sequence, as I understand it) by checking the SEQ.PACT field prior to starting the sequencer. Perhaps I'm missing something here.

**Comment by klauer** [comment]
I don't know much about the sequencer, but `PACT` _in general_ is likely to be high for only a very short period of time (the duration of processing the record chain). If that's the case here, too, it's not really worth checking it, I'd think.

**Comment by ZLLentz** [comment]
@slactjohnson I didn't put much thought into the "how" or if it would be feasible, but I think I got a few of my wires crossed, the status object from trigger has nothing to do with the reconfiguration.
