### ISSUE TITLE
Epics Motor Homing Button Easy to Accidentally Hit in Typhos Screens

### ISSUE THREAD

**Issue by ZLLentz** [pcdshub/pcdsdevices#722]
## Expected Behavior

It should be hard to press the homing button accidentally (in general, it should be hard to move motors accidentally)
https://slac.slack.com/archives/CV0S7HSPK/p1607363608008000?thread_ts=1607189599.005600&cid=CV0S7HSPK

## Current Behavior

The homing buttons show up very prominently when opening the screen

## Possible Solution

- Reduce from `normal` to `config`? For all motors or just for Beckhoff?
- Add variety handling for "button with confirm dialog"

## Context

Matt asked questions about homing buttons in the #pcds-ui channel in thread https://slac.slack.com/archives/CV0S7HSPK/p1607189599005600

## Your Environment

pcdsdevices and typhos master as of 12/7/2020 at 10am

**Comment by klauer** [comment]
For reference on possible solution (2):
The `confirm` tag:
https://github.com/pcdshub/pcdsdevices/blob/5ee91018658423b297e17a242f72b09bfcefc87e/pcdsdevices/tags.py#L3
is supported by `TyphosCommandButton`:
https://github.com/pcdshub/typhos/blob/f24d1db21d7711fda5241897188d8fc95db0238b/typhos/widgets.py#L569

**Comment by ZLLentz** [comment]
The problem that sparked this issue happened again, maybe should do
