### ISSUE TITLE
Missing jsonschema dependency

### ISSUE THREAD

**Issue by ZLLentz** [pcdshub/pcdsdevices#756]
Compare:
https://github.com/pcdshub/pcdsdevices/blob/d08d4ed516d5831929dc46cedd8dbf80b42fbe85/pcdsdevices/targets.py#L10
https://github.com/pcdshub/pcdsdevices/blob/d08d4ed516d5831929dc46cedd8dbf80b42fbe85/conda-recipe/meta.yaml#L20-L33

**Comment by klauer** [comment]
For reference:
* `schema` is the one from `pcdsdevices.variety` (serialization-agnostic)
* `jsonschema` is the one from `pcdsdevices.targets` (JSON-specific)

**Comment by klauer** [comment]
I'm surprised we never got around to this... bump

**Comment by ZLLentz** [comment]
let's pull this in prior to the tag
