### ISSUE TITLE
InstanceComponent

### ISSUE THREAD

**Issue by ZLLentz** [pcdshub/pcdsdevices#780]
## Expected Behavior

Random idea that I had last night.
For one-off devices in beamline setup files, it might be useful to have a construct like:

```
from ophyd import Device, EpicsSignal
from pcdsdevices.component import InstanceComponent as ICpt

my_signal = EpicsSignal('MY:PV')

class MyDevice(Device):
    sig = ICpt(my_signal)
```

So that we can build things like one-off pseudo positioners using existing motor objects constructively rather than duplicatively.

This would never be acceptable in `happi` or even useful at all in applications outside of a single hutch's operations, but I think it could be helpful where users don't really want to know implementation details like `'MY:PV'` but do want to assemble interesting devices.

**Comment by klauer** [comment]
I think it's a neat idea, and I think it'll work as you propose. Thinking along those lines...

If we had a separate set of `DeviceInterface` classes that defined an interface of component names, hierarchy, and (whatever else is necessary), it may be a good in-road for `PVPositioner`-style of classes that are actually created on a one-off basis - i.e., when instantiated. 

That is, `MyDevice(sig=my_signal)` which would have an interface definition of `ICpt(EpicsSignal)` (which would reject an `EpicsMotor` instance unless it had something like `ICpt(EpicsMotorLikeInterface)`). There could be helper functions like `interface_from_device(EpicsMotor)` and such, too.

Not sure if I like what I'm suggesting above, but it's just a thought 🤷‍♂️
