### ISSUE TITLE
Various Components Incorrectly Set as Hinted

### ISSUE THREAD

**Issue by ZLLentz** [pcdshub/pcdsdevices#782]
## Expected Behavior

When we scan a motor we should only see the changing quantities in the live table.

## Current Behavior

```
In [47]: lxt_ttc.hints
Out[47]:
{'fields': ['lxt_ttc_lxt_setpoint',
  'lxt_ttc_lxt_notepad_setpoint',
  'lxt_ttc_lxt_notepad_readback',
  'lxt_ttc_lxt_user_offset',
  'lxt_ttc_txt_delay',
  'lxt_ttc_txt_delay_notepad_setpoint',
  'lxt_ttc_txt_delay_notepad_readback',
  'lxt_ttc_txt_user_offset',
  'lxt_ttc_txt_motor']}
```
But only `lxt_ttc_lxt_setpoint` (`LaserTiming.setpoint`) and `lxt_ttc_txt_motor` (`DelayNewport.motor`) belong here.

**Comment by ZryletTC** [comment]
I'm pretty sure this stems from a bug in `NotepadLinkedSignal`, where it's `kind` can't be set properly. It looks like this was never turned into an issue though, we've only talked over Slack:

> Tyler Pennebaker Dec 1st, 2020 at 3:47 PM
> This is how you omit components, right?
>     notepad_readback = Cpt(NotepadLinkedSignal, ':lxt:OphydReadback',
>                            notepad_metadata={'record': 'ao', 'default_value': 0.0},
>                            kind='omitted')
>
> Ken Lauer  3 months ago
> omit for the purposes of bluesky or typhos user interfaces? yes
> 
> Tyler Pennebaker  3 months ago
> yup
> 
> Tyler Pennebaker  3 months ago
> Hmm, weird. That component is still showing up as hinted in xpp3
> 
> Tyler Pennebaker  3 months ago
> Maybe something else is messing with it, I’ll do some more digging
> 
> Ken Lauer  3 months ago
> there may be a hack somewhere that tweaks the first signal to be hinted
> 
> Ken Lauer  3 months ago
> i can't recall where that might be living though
> 
> Tyler Pennebaker  3 months ago
> Right, I do remember that now. But this isn’t the first component…
> 
> Ken Lauer  3 months ago
> odd
> 
> Ken Lauer  3 months ago
> did you figure this one out @tntp?
> 
> Tyler Pennebaker  3 months ago
> Nope
> :hmmm:
> 1
> 
> 
> Tyler Pennebaker  3 months ago
> I just ignored it for now cause there are bigger fish to fry
> 
> Ken Lauer  3 months ago
> hmm, ok
> 
> Tyler Pennebaker  3 months ago
> If you have any more input, I’d be happy to jump back on it and try stuff out though
> 
> Ken Lauer  3 months ago
> turns out the _OptionalEpicsSignal is at fault here
> 
> Tyler Pennebaker  3 months ago
> ohh :confused:
> 
> Tyler Pennebaker  3 months ago
> How so? I don’t see any explicit kind assignments. I also only barely glanced over it so I definitely missed it (edited) 
> 
> Ken Lauer  3 months ago
> yeah, so the way it works is that it stashes an EpicsSignal that it optionally uses - based on connection status, but the object itself also has a kind which is getting reported here
> 
> Ken Lauer  3 months ago
> the fix is to proxy the internal epics signal's kind, like the other properties
> 
> Tyler Pennebaker  3 months ago
> Ahh got it, I’ll try that out. Thanks :slightly_smiling_face:
> :npm:
> 1
> 
> 
> Tyler Pennebaker  3 months ago
> Hmm that seems to fail because ophydobj wants to set its kind and the proxy is currently only readonly
> 
> Ken Lauer  3 months ago
> yeah, looks like it's a bit more complicated: https://gist.github.com/klauer/bee78eeae655ec093d2460d09788e304
