### ISSUE TITLE
CoatingState should not have OUT state

### ISSUE THREAD

**Issue by ZryletTC** [pcdshub/pcdsdevices#812]
## Expected Behavior
Instantiating an `XOffsetMirrorState` object doesn't raise any exceptions.

## Current Behavior

```
ERROR    Subscription meta callback exception (EpicsSignal(read_pv='MR2L0:HOMS:COATING:STATE:GET_RBV', name='mr2l0_homs_coating_state', parent='mr2l0_homs_coating', timestamp=1617385934.76241, auto_monitor=False, string=False, write_pv='MR2L0:HOMS:COATING:STATE:SET', limits=False, put_complete=False))
Traceback (most recent call last):
  File "/u1/xppopr/conda_envs/pcds-3.5.0/lib/python3.6/site-packages/ophyd/ophydobj.py", line 462, in inner
    cb(*args, **kwargs)
  File "/reg/g/pcds/pyps/apps/hutch-python/xpp/dev/devpath/pcdsdevices/state.py", line 112, in _late_state_init
    self._state_init()
  File "/u1/xppopr/conda_envs/pcds-3.5.0/lib/python3.6/site-packages/ophyd/device.py", line 1620, in wrapped
    ret = func(self, *args, **kwargs)
  File "/reg/g/pcds/pyps/apps/hutch-python/xpp/dev/devpath/pcdsdevices/inout.py", line 76, in _state_init
    self._extend_trans_enum(self.out_states, 1)
  File "/reg/g/pcds/pyps/apps/hutch-python/xpp/dev/devpath/pcdsdevices/inout.py", line 138, in _extend_trans_enum
    self._update_trans_enum(state, default)
  File "/reg/g/pcds/pyps/apps/hutch-python/xpp/dev/devpath/pcdsdevices/inout.py", line 141, in _update_trans_enum
    index = self.states_list.index(state)
ValueError: 'OUT' is not in list
```

## Possible Solution

The `coating` attribute of the mirror object is a `TwinCATStatePMPS` which inherits from `InOutPositioner` and therefore has the attribute `out_states = ['OUT']` and uses it during `_state_init()`. However, the PV `MR2L0:HOMS:COATING:STATE:GET_RBV` only has 3 possible values: `Unknown`, `B4C`, and `B4C_Ni`, with no `OUT` state.

I'm guessing the coating state should not be an `InOutPositioner`. Thoughts? @ghalym 

## Context
Just noticed this when loading up xpp3.

## Your Environment
xppenv (pcds-3.5.0 + current master pcdsdevices)

**Comment by ghalym** [comment]
@ZryletTC yes, I agree. I guess we need to create another generic StatePositioner class. All the L line optics will have these coating states and there is no defined out state for them.

**Comment by ZLLentz** [comment]
This is a pretty easy fix, no need to panic. We either use the existing generic state positioner class or we set `out_states = []` (empty list)

**Comment by ZLLentz** [comment]
I think to make it work easiest with the existing applications we just set `out_states = []` in the coating states definition

**Comment by ghalym** [comment]
@ZLLentz So we need to add out to the enums?

**Comment by ZLLentz** [comment]
No, we remove OUT from the expected enums lists on the python side

**Comment by ZLLentz** [comment]
See parent class: https://github.com/pcdshub/pcdsdevices/blob/be5cfea9b6d306013122c1fff3d2cbab67e7fdc7/pcdsdevices/inout.py#L55

**Comment by ZLLentz** [comment]
I'll do a quick PR

**Comment by ghalym** [comment]
And that wouldn't break anything for the other In/Out devices... Something in light path maybe...

**Comment by ZLLentz** [comment]
lightpath will be like "oh, I guess this device is always in the way!"
so I guess I have to also put in a bit that says "this device doesn't block the beam" as well
