### ISSUE TITLE
Docs building missing many classes; needs reworking

### ISSUE THREAD

**Issue by klauer** [pcdshub/pcdsdevices#820]
## ~Expected~ Hopeful Behavior
The `autodoc` stuff should outline `pcdsdevices` without issue, to give a full view of the package.

## Current Behavior
We have a subset of modules listed, and only a subset of class documentation is generated.

## Possible Solution
Look into how to make this better.

## Steps to Reproduce (for bugs)
Take a look at the built docs now for `FuncPositioner`; it won't be there.
Adding modules to the "Full API" page leads to scenarios where the generated source is excessive and takes forever to build:
`source/generated/generated/generated/generated/.../generated/pcdsdevices.foo.bar.html`

## Context
We need docs!

**Comment by ZLLentz** [comment]
I think the approach here should be to:
- Dismantle the recursive autosummary mechanisms here, leaving just the ophyd doc utilities behind: https://github.com/pcdshub/pcdsdevices/tree/master/docs/source/_templates/autosummary
- create api/<module>.rst pages by hand that call automodule once
- make api.rst a simple toctree for the api sub-pages

This will build faster, be easier to debug, and be fully complete at the expense of requiring a new docs/source/api/module.rst page to be made each time we add a new submodule- perhaps we can write a CI check to verify that we have 1:1 correspondence, or a simple script that generates the whole api subfolder ahead of time.

**Comment by ZLLentz** [comment]
(also, smaller reminder to fix how the sample delivery api page erroneously shows as a top-level API page, baiting me into clicking on it all the time when I'm really after the full api page)

**Comment by klauer** [comment]
That sounds like a good plan, @ZLLentz  👍

**Comment by ZryletTC** [comment]
I agree, that sounds much better than what we have going at the moment 🚀 👍
