### ISSUE TITLE
Add class for ICT DC distribution chassis

### ISSUE THREAD

**Issue by slactjohnson** [pcdshub/pcdsdevices#860]
## Expected Behavior
It would be nice to have a class for these devices, primarily for Typhos/LUCID screen generation. 

## Current Behavior
I don't see a class for these yet. 

## Context
I am not aware of an easy way to interact with these systems yet, other than via caget/put. I don't see any screens in the ioc/common/ict repo. It would be nice to have a screen for these to check on status and enable simple power cycling of devices as needed.

**Comment by ZLLentz** [comment]
Is this different than the classes at https://github.com/pcdshub/pcdsdevices/blob/master/pcdsdevices/dc_devices.py?

**Comment by slactjohnson** [comment]
Nope, I'm just an idiot and didn't see that module. Looks like just what I wanted. Thanks Zach!

**Comment by ZLLentz** [comment]
I also did not see that module when I saw this issue yesterday- it was only today where I was readying through every single file in pcdsdevices that I saw it!

**Comment by slactjohnson** [comment]
At least I'm not the only one. :) 

This repo is getting pretty dense. Maybe time for some restructuring?

**Comment by ZLLentz** [comment]
It is 100% in need of restructuring.

**Comment by klauer** [comment]
One day: https://github.com/pcdshub/pcdsdevices/issues/413
