### ISSUE TITLE
CCM format_status_info exception handling insufficient

### ISSUE THREAD

**Issue by klauer** [pcdshub/pcdsdevices#908]
https://github.com/pcdshub/pcdsdevices/blob/7023cb7fe4a85b05293971a7726f066945ea3081/pcdsdevices/ccm.py#L982

in `xcspython` on `psbuild-rhel7`, I was trying to look at what devices were loaded, and found that `CCM` `format_status_info` exception handling was insufficient to catch the scenario where x_down and such were strings.

Beyond that, I think `format_status_info` in general needs to be more resilient, perhaps having a fallback repr when exceptions are raised.

Their env is 4.2.0, but the code in question I do not believe has changed. Regardless, the larger issue should be addressed at some point.

Message
--------
```
/cds/group/pcds/pyps/apps/hutch-python/xcs/dev/devpath/pcdsdevices/ccm.py in format_status_info(self, status_info)
    980                                 precision=3)
    981         try:
--> 982             xavg = np.average([float(x_down), float(x_up)])
    983             xavg = f'{xavg:.3f}'
    984         except TypeError:

ValueError: could not convert string to float: 'ERROR'
```

**Comment by ZLLentz** [comment]
Where exactly is `format_status_info` being called from in this case? Is this directly from the `status` method? I notice that the `status` method doesn't have any error handling, but the `_repr_pretty` does https://github.com/pcdshub/pcdsdevices/blob/7023cb7fe4a85b05293971a7726f066945ea3081/pcdsdevices/interface.py#L257-L270

**Comment by ZLLentz** [comment]
Nevermind, it says `raise` and I don't know why that line is there
