### ISSUE TITLE
Discussion: should _repr_pretty_ ever raise?

### ISSUE THREAD

**Issue by klauer** [pcdshub/pcdsdevices#909]
https://github.com/pcdshub/pcdsdevices/blob/7023cb7fe4a85b05293971a7726f066945ea3081/pcdsdevices/interface.py#L257-L264

Related to #908 

Looking at git blame, I may have added this as a debugging tool, but I never removed it and it wasn't caught in review. I may be mistaken here, though.

**Comment by ZLLentz** [comment]
I think it should be removed, UI should never get in the way of the user.
