### ISSUE TITLE
Feature: DerivedSignal with multiple sources

### ISSUE THREAD

**Issue by klauer** [pcdshub/pcdsdevices#969]
## Current / Expected Behavior
* `DerivedSignal` allows us to take in a single signal and perform some calculations on it, and make a new signal
* It should be possible to take in multiple input signals and, whenever one changes, perform some calculations on it and publish a new signal

## Possible Solution
It could be called `MultiDerivedSignal` or something like that.
`Cpt(MultiDerivedSignal, attrs=["attr1", "attr2", "attr3"])`

## Context
Talking with Mike E. about how to approach summarizing error codes from 19 x 3 locations (for each attenuator blade: motor, state, PLC error codes) in a single signal that can be displayed readily in typhos or used in hutch-python.

**Comment by ZLLentz** [comment]
We made this ages ago, but maybe it still has some relevance: https://github.com/pcdshub/pcdsdevices/blob/4db5c7ddab1f8842b865cb31c751208cb9745081/pcdsdevices/signal.py#L119

**Comment by klauer** [comment]
I think even if there is really no issue with AT2L0 (based on our internal conversations) this is still worthwhile to have. The class provided by @ZLLentz above will serve as a perfect basis for the implementation after a couple tweaks.
