### ISSUE TITLE
Add a reconnect method to the daq class

### ISSUE THREAD

**Issue by apra93** [pcdshub/pcdsdevices#99]
## Expected Behavior

You enter `daq.reconnect()` and it simply disconnects and reconnects.

## Current Behavior

Not implemented

## Context

Scientists manually `disconnect()` and `connect()` between everything they do (every scan attempt)

**Comment by ZLLentz** [comment]
Any insight as to why scientists manually disconnect and connect between scans? I can't imagine any reason for this.

**Comment by ZLLentz** [comment]
@apra93 Closing because `daq` class was moved to a different module, and I don't see a need for this. Calling `disconnect` is the same as calling `reconnect` because the `daq` will automatically `connect` when it needs to. I think this is user error.
